### ISSUE TITLE
Suggest a glossary term for an app

### ISSUE THREAD

**Issue by sammyfilly** [ethereum/ethereum-org-website#10539]
### Checklist

- [X] This is a term not already found in the glossary (for similar terms, please consider the benefits of a new term vs updating an existing term)
- [X] This term/definition is not a product advertisement or contain other promotional content
- [X] This term/definition is directly relevant to Ethereum

### Term name

ethereum developer

### Term definition

a correction to a bug in a computer program or system.

### Sources, if any (please do not submit copywrited content without appropriate approval)

few from ethereum.org 

### Ethereum.org links

https://ethereum.org/en/

### Would you like to work on this issue?

- [X] Yes
- [ ] No
```[tasklist]
### Tasks
- [x] https://crowdin.com/project/ethereum-org
- [ ] https://github.com/ethereum/ethereum-org-website/issues/10538
```
