### ISSUE TITLE
Adding Crossmint to the list of Enterprise Developer Resources

### ISSUE THREAD

**Issue by rohit-710** [ethereum/ethereum-org-website#11636]
### Dev tool name

Crossmint

### Dev tool description

Crossmint is the leading enterprise-grade web3 development platform, allowing you to build NFT applications without requiring any blockchain experience or holding cryptocurrency, and making the blockchain invisible to end users. The platform offers a one-stop-shop for most of your NFT infrastructure needs across all major chains, including creating, distributing, selling, storing digital assets, and offering post-mint utility. 

### When did the dev tool go live?

February, 2022

### Where do you think this page should be shown?

https://ethereum.org/en/enterprise/#enterprise-developer-resources
Under this page, under "Products and services".

https://ethereum.org/en/enterprise/#enterprise-live-on-mainnet
Under this page, under "Payments"

### Is the product open source?

No

### GitHub URL

https://github.com/Crossmint

### Documentation URL

https://docs.crossmint.com/

### Would you like to work on this issue?

- [x] Yes
- [ ] No

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/ethereum-org-website/pull/11684
- [ ] https://github.com/ethereum/ethereum-org-website/pull/11683
- [ ] https://github.com/ethereum/ethereum-org-website/pull/11685
```

**Comment by shubhusion** [comment]
kindly assign this issue to me

**Comment by rohit-710** [comment]
@shubhusion Unable to add assignees for some reason

**Comment by shubhusion** [comment]
@rohit-710 are you a maintainer ?

**Comment by rohit-710** [comment]
Nope, I just opened this issue to get it added on the docs. Unable to assign it to anyone

**Comment by rohit-710** [comment]
https://github.com/ethereum/ethereum-org-website/pull/11685
https://github.com/ethereum/ethereum-org-website/pull/11683
https://github.com/ethereum/ethereum-org-website/pull/11685

**Comment by rohit-710** [comment]
Hey @wackerow @corwintines @pettinarip @minimalsm @nhsz 

Can you guys please take a look at this issue that I worked on? It's been open for a while now

I have already made the PRs for this. Kindly take a look and merge it if everything looks good!

**Comment by wackerow** [comment]
Hey @rohit-710! Apologies for the delays here. We're still working our way through issues and PRs that built up during Q4 of last year after most of the dev hours on the team were dedicated to the Next.js migration. I see the three PRs and will review them now 🙏

**Comment by rohit-710** [comment]
> Hey @rohit-710! Apologies for the delays here. We're still working our way through issues and PRs that built up during Q4 of last year after most of the dev hours on the team were dedicated to the Next.js migration. I see the three PRs and will review them now 🙏

Hey @wackerow, thanks for getting back to me! I just responded to all of your comments and made the necessary changes that you had requested. 

Let me know if it looks good to go

**Comment by wackerow** [comment]
@rohit-710 The original issue here had suggested adding to the Enterprise page, but I see the three PRs above request addition to:

- `/developers/docs/smart-contracts/`
- `/developers/docs/frameworks/`
- `/developers/docs/dapps/`
- `/enterprise/` (x3 locations)

How would you prioritize these in terms of best alignment with Crossmint?

**Comment by rohit-710** [comment]
@wackerow I have removed the occurrence of multiple references within the `enterprise` page. 

I believe it fits between all of the 4 pages of the docs, if that makes sense. Would it be a problem to add it to those 4 pages? Please let me know

**Comment by rohit-710** [comment]
Hey @wackerow, when do the changes appear on the docs? All the 3 PRs seem to have been deployed by Mintlify but I am unable to view it on the docs page. Please let me know 🙏

**Comment by wackerow** [comment]
@rohit-710 `dev` branch is deployed to staging every two weeks by Wednesday, then into `master` usually on Thursday... these should be live in about two days.
