### ISSUE TITLE
Rethinking L2 information on ethereum.org 

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13062]
### Is your feature request related to a problem? Please describe.

Blobs are here and layer 2 activity is surging. The focus of ethereum.org has always been Ethereum Mainnet (L1), but these rapid scaling infrastructure improvements make it clear that ethereum.org should grow into a more comprehensive resource for the Ethereum ecosystem. 

We are in the early stages of planning this transition and welcome your thoughts.

[Join in on the discussion in Discord](https://ethereum.org/discord)

### Describe the solution you'd like

- [x] - small revamp of https://ethereum.org/en/wallets/find-wallet/ to include "networks supported by wallets" data
- [x] - rethink https://ethereum.org/en/layer-2/ content
- [x] - take L2 listings out of https://ethereum.org/en/layer-2/ and create a new page dedicated to L2 listings
- [x] - change https://ethereum.org/en/what-is-ethereum/ "what is ethereum summary" to explain better ethereum and its relation to the ecosystem
- [ ] rethink dapp listings on https://ethereum.org/en/dapps/
- [x] include L2 info on redesigned new homepage for ethereum.org

Any other suggestions? Feel free to comment here or on discord!

### Describe alternatives you've considered

NA

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by konopkja** [comment]
update: designs are ready - waiting for implementation

**Comment by konopkja** [comment]
Update: designs have been prepared and this Q3 will implementation happen. Once the designs are done, this issue will be closed.

Afterwards we will do UX research to monitor impact of the results.

**Comment by konopkja** [comment]
Update: Implementation has started few weeks ago and should be finalized in Q3.

**Comment by corwintines** [comment]
Removing stale, we are finishing up implementation and will  link that PR to this when ready

**Comment by konopkja** [comment]
An upgrade to our website has been prepared and soon shipped, with that i am clsing this ticket
