### ISSUE TITLE
Epic: Find Wallet page revamp

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#6274]
## **Epic Description**
Context: Epic from Q2 Roadmap https://github.com/ethereum/ethereum-org-website/issues/6161

[/wallets/find-wallet](https://ethereum.org/en/wallets/find-wallet/) page gets roughly 5.5% of site views, which is a large amount of traffic. Finding a wallet is an integral piece to onboarding into Ethereum. 

Looking at the analytics we currently drop off to about 50% of users after a few rows in the section listing wallets. This section is randomized, meaning where users may be stopping their journey could be on a suboptimal wallet depending on their use case. There are also extra actions needed for the user to see features for that wallet, which would be better if we could get that information upfront.

This quarter we will work on rebuilding the [/wallets/find-wallet](https://ethereum.org/en/wallets/find-wallet/) page, and improving the experience for users looking for wallets with specific features. We will build user profiles to help filter wallets down for users (while allowing them to still skip this altogether) to help find the best wallet for their particular use case, in addition to improving the user experience for using feature filters to filter down wallets. We will also improve the wallet product card to make information easier to find, and give a better experience when comparing wallets.

With these changes in features for wallets, we will be updating the listing policy that wallets fill out to be featured on ethereum.org. A number of new features for wallets have come out in the last 2 years, and our listing policy will be updated to reflect this.

## **Links**
Some links to follow along with the design process
Figma: Will be shared at a later date

## **To do:**
- [x] Update wallet source of truth with updated feature information
- [x] Update listing policy for wallets
- [x] Create a new design for the find-wallets page
- [x] Implement new design into ethereum.org codebase
- [x] Release and gather feedback

## **Resources:**
The ongoing design work for this epic will be done in this [Figma](https://www.figma.com/file/VfAtok8dxIxQf6hYA4Cghu/Wallet-EPIC?node-id=67%3A343) file.
Feel free to comment

**Comment by ligi** [comment]
Would love to throw this issue in the ring: https://github.com/ethereum/ethereum-org-website/issues/2715 - maybe some ideas from there can be used in the revamp

**Comment by kuzdogan** [comment]
It would be nice to have a filter for transaction decoding + documentation. 

In short it is possible to decode the function parameters by pulling the ABI. If the wallet uses Sourcify (i.e. contract metadata) it can both decode via ABI + show the function's NatSpec user documentation, instead of a hex string.

**Comment by konopkja** [comment]
user profiles can be opted in, but not opted out. 

steps to reproduce: 
1. when you load page no profile is selected, 2. you select a profile and list of wallets is filtered, 3. i want to reset the view and see all. 4. clicking on the selected profile does not deselect it and i cant see the full list again

**Comment by konopkja** [comment]
<img width="332" alt="Screenshot 2022-06-15 at 20 23 37" src="https://user-images.githubusercontent.com/100724231/173865405-c386ab43-4dc2-4d35-99ed-7c48a259f7a7.png">

currently only the checkbox are is clickable, ideally the text + checkbox should be clickable.

**Comment by konopkja** [comment]
<img width="244" alt="Screenshot 2022-06-17 at 19 12 42" src="https://user-images.githubusercontent.com/100724231/174315823-be97ad05-2751-4d17-917d-e661a6f579a5.png">

just small thing noticed paddings arent consistent on mouse over

**Comment by konopkja** [comment]
<img width="346" alt="Screenshot 2022-06-17 at 19 16 12" src="https://user-images.githubusercontent.com/100724231/174320925-0275fa9d-a314-4bee-a6df-6f2e7c9a1328.png">

the background and the text need some work when a profile is selected
