### ISSUE TITLE
Epic: pre-merge prep

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#6281]
Context: Epic from Q2 Roadmap https://github.com/ethereum/ethereum-org-website/issues/6161

## Epic Description
After a long wait, the Merge is almost upon us. The switch to proof-of-stake means that large sections of ethereum.org will need rewriting to remain up to date. 

## Involves 
- Scoping out what content changes, additions, or subtractions are required related to the Merge upgrade
- Preparing appropriate content changes, 
- Coordinating with external contributors to ensure accuracy
- Timing releases  appropriately to provide the community with accurate information about the Merge during the transition

## Goals
**Pre-Merge Prep**
- Help clear up misconceptions of **every day users** regarding how the Merge will be executed, and the impact it will/will not have. Also reassuring these users that there is nothing they need to do with their funds.
- Inform **dapp developers** of important changes that may result from the Merge
- Inform **node operators** of important changes, including the need to run both an execution layer (EL) client as well as a consensus layer (CL) client to sync the head of the chain
- Inform **stakers** of important changes, including that their nodes will require the above CL+EL setup, and they will need to provide a traditional Ethereum address to receive unburnt fees in blocks they propose

**Post-merge, longer-term changes\***
- Ensure references to proof-of-work are updated to either be historical references, or removed
- Update developer documentation to ensure all fundamentals are accurately represented under the proof-of-stake model
- Update `/upgrade/merge` and to be reflective of past tense and latest information
- Update `/energy-consumption` page with updated latest information

## Checkpoints
[Page Audit Spreadsheet](https://docs.google.com/spreadsheets/d/1Nisi3_FY8nwOlLwPsTPm0jlgtAhypH0-pjatGDMSz7M/edit#gid=0)

**Pre-merge update PR:**

- [x] Banner notification: some page content may be out of date related to the merge #6629
  - /developers/docs/consensus-mechanisms/pow/mining-algorithms/
  - /developers/docs/development-networks/
  - /developers/docs/intro-to-ether/
  - /developers/docs/mev/
  - /developers/docs/mining/
  - /developers/docs/networking-layer/
  - /developers/docs/networks/
  - /developers/docs/nodes-and-clients/
  - /developers/docs/nodes-and-clients/client-diversity/
  - /developers/docs/nodes-and-clients/nodes-as-a-service/
  - /developers/tutorials/run-light-node-geth/
  - /developers/tutorials/run-node-raspberry-pi/
  - /nft/
- [x] Follow-up PR with expanded banner functionality, tagging a few more pages #6710
  - / (Homepage)
  - /developers/
  - /developers/docs/
  - /developers/docs/blocks/
  - /developers/docs/dapps/
  - /developers/docs/gas/
  - /developers/docs/transactions/
  - /developers/docs/intro-to-ethereum/
  - /developers/docs/data-and-analytics/block-explorers/

Content updates:
- [x] / (Homepage, preMergeBanner only before merge) #6710
- [x] /developers/ (Developers landing, preMergeBanner only before merge) #6710
- [x] Developer docs
  - [x] /developers/docs/ (Docs landing, preMergeBanner only before merge) #6710
  - [x] /developers/docs/consensus-mechanisms/pow/mining-algorithms/ #6782
  - [x] /developers/docs/development-networks/ #6660 
  - [x] /developers/docs/intro-to-ether/ #6756
  - [x] /developers/docs/mev/ #6780
  - [x] /developers/docs/mining/ #6685
  - [x] /developers/docs/networking-layer/ #6684 
  - [x] /developers/docs/networks/ #6756
  - [x] /developers/docs/nodes-and-clients/ #6756
  - [x] /developers/docs/nodes-and-clients/client-diversity/ #6661 
  - [x] /developers/docs/nodes-and-clients/nodes-as-a-service/ #6756
  - [x] /developers/docs/nodes-and-clients/run-a-node/ #6806
  - [x] /developers/tutorials/run-light-node-geth/ #6657 
  - [x] /developers/tutorials/run-node-raspberry-pi/ #6756
- [x] Upgrades
  - [x] /upgrades/ #6641 
  - [x] /upgrades/beacon-chain/ #6647
  - [x] /upgrades/merge/ #6599
  - [x] /upgrades/shard-chains/ -> /sharding/ #6674
  - [x] /upgrades/vision/ #6698
  - [x] /upgrades/get-involved/ #6646 
- [x] Other pages
  - ~~/community/support/~~
  - ~~/contributing/style-guide/~~
  - [x] /energy-consumption/ #6599
  - [x] /eth/ #6700 
  - ~~/governance/~~
  - ~~/learn/~~
  - [x] /nft/ (Banner only before merge #6629)
  - ~~/security/~~
  - [x] /staking/ #6699 
  - ~~/staking/deposit-contract/~~
  - [x] /staking/solo/ #6699 
  - [x] /staking/saas/ #6699 
  - [x] /staking/pools/ #6699 

**\* 29-Jun-2022 Update re: post-merge changes:**
Given the time gap between the need to roll out the above "pre-merge" content, and the eventual "post-merge" changes that will update the site once The Merge has officially been completed, these two phases of content updates have been broken into two separate epics.

A separate epic tracking issue will be posted for Q3 to track progress of content preparation, with plan to release these updates as a bundle after a successful transition to proof-of-stake.

[Notion Epic Card](https://www.notion.so/efdn/Merge-prep-ethereum-org-08d62522d78d449b9149e0766c69ca39)

**Comment by samajammin** [comment]
@wackerow I believe this is complete & can be closed out 🎉 

Please re-open if I'm wrong 😄

**Comment by Ghetto21** [comment]
Epi: pre merge prep# 6281
Closed
