### ISSUE TITLE
Epic: translation quality

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#6282]
Context: Epic from Q2 roadmap #6161 

**Epic Description**

As part of an ongoing effort to track and improve translation quality, we want to research the best processes, tools, and metrics to achieve this. We will be performing QA to identify and fix the most common issues in translations for individual languages, researching QA tools that work best with Crowdin and ethereum.org content, and exploring ways to track translation quality over time.

**Goals**

- Perform QA for all translations
- Add a QA step to the translation process 
- Identify common errors and issues in translations
- Track translation quality over time

**Checklist**

- [x] Perform initial QA for all languages in Crowdin
- [x] Identify ways to track translation quality over time
- [x] Track most common inconsistent translations
- [x] Identify the best QA tool and process to use
- [x] Add QA step to the translation process
- [x] Perform 2nd round of QA
- [x] Track translation quality over time
