### ISSUE TITLE
Epic: Ethereum for educators

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#6283]
Context: Epic from Q2 roadmap #6161 & Q3 roadmap #7166
**Epic Description**

Add a section to the website for educators and lecturers, looking to teach about Ethereum or create courses. This section should include resources for creating courses and curriculums, related to Ethereum, other teaching resources, and case studies that educators could use, addressing the lack of clear framework for educators setting up courses. It could also include a list of existing Ethereum or blockchain courses and universities, as well as skill trees and internship opportunities for learners.

**Goals**

- Ship an Ethereum for educators page
     - Include courses and curriculums
     - Case studies
     - List of existing courses
     - Listing policy

**Checklist**

- [x] Identify and reach out to contributors
- [x] Create a list of potential resources to be added
- [x] Gather resources
- [ ] Design page
- [ ] Draft content
- [ ] Build page
- [ ] Gather feedback on page
- [ ] Iterate
- [ ] Set up page for translations

**Comment by Robert-75** [comment]
Are the gathered resources public?

**Comment by polarpunklabs** [comment]
Hi folks, I am building Case Studies for my module The Ethereum Ecosystem: https://hub.ucd.ie/usis/!W_HU_MENU.P_PUBLISH?p_tag=MODULE&MODULE=MIS41220

It might make sense if rather than us both making them I could make them and then open source them for use on the website. I'd need a little bit of funding here and help with connecting with people that could make the Case Studies impactful (e.g. actual DAO community managers at a major DeFi protocol, etc.).

I would also want to stress it's important we don't end up with a bunch of technical resources. This is a common trap in blockchain communities. The non-technical modules, guides, resources, etc. should be given equal billing.

**Comment by Robert-75** [comment]
I'm also working on a general blockchain course with the most emphasis on Ethereum. The course is for intermediate IT students. Would appreciate help on this.

**Comment by lukassim** [comment]
Closing this out as it's no longer a top priority but please comment if you'd like to contribute to this initiative!
