### ISSUE TITLE
Epic: Implement UI library

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#6374]
*This is an epic that makes up part of [the ethereum.org Q3 roadmap](https://github.com/ethereum/ethereum-org-website/issues/7166)*

### **Description**

A major insight from our research into accessibility and our website audits last quarter was that many of the issues we face, like lack of keyboard navigation, support for assistive technology and consistent W3C design patterns can be solved out-of-the-box by adopting an open source UI library.

Ultimately we’ve come to believe that rolling our own robust components is not what we should focus our time on. Leveraging an existing UI library will save our development and design team time to focus more energy on what matters - shipping products for our Ethereum users. This effort also ties in well with our work on the open design system and will serve as the foundation to our component library.

### **Todo**

- [x]  Decide which UI lib to use
    - We are going to use [Chakra](https://chakra-ui.com/) ([see a summary of our research](https://www.notion.so/Research-options-and-select-UI-library-babae0a343e24c92be0d6bd486e35c1c))
- [x]  Finish TS migration of the codebase (#6392)
- [x] #7054
- [x] #7196
- [x] #7374
- [x] #7369
- [x] Bump Chakra to v2 #7617 
- [x] Migrate each one of our UI components
  - [x] First wave
  - [x] #8632
- [x] #9353
- [x] #10562
- [ ] cleanup tasks: clean `SharedStyledComponents`, update docs, and remove deprecated components #10575

### **How to contribute**

If you’d like to help with this migration, please follow these steps:

1. Leave a comment here asking which file you would want to work on.
2. We assign you to the file (by adding your handle next to the file name in the list).
    - Read and follow our [UI migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md) for some tips & guidance.
    - **If you were assigned to multiple files** then create a separate PR for each component. It will make the testing process much simpler and more organized.
3. Once you finish it (PR merged), we’ll mark it as done.
4. Repeat!

----

<details>
  <summary>First wave (completed)</summary>
  
- [x]  `src/components`
    - [x] ~Accordion.tsx @SNikhill~
    - [x]  ActionCard.tsx @SNikhill #8009
    - [x]  AdoptionChart.tsx @soheil555 #9088
    - [x]  AssetDownload.tsx @benlazzero #9103
    - [x]  BannerNotification.tsx @Mousticke #7778
    - [x]  BoxGrid.tsx @soheil555 #9094
    - [x]  Breadcrumbs.tsx @Master7130 #8641
    - [x]  BugBountyCards.tsx @Marcelixoo #8739
    - [x]  CallToContribute.tsx @vdusart #7975
    - [x]  Callout.tsx @vdusart #7750
    - [x]  CalloutBanner.tsx @vdusart #7869
    - [x]  Card.tsx @vdusart #7755
    - [x]  CardList.tsx @pettinarip #7721
    - [x]  Checkbox.tsx @marcellamalune #8204
    - [x]  CodeModal.tsx @LuisUrrutia #8006
    - [x]  CopyToClipboard.tsx @frankiefab100 #8318
    - [x]  DataProductCard.tsx @LuisUrrutia #8015
    - [x]  ~~DismissibleCard.tsx @MahendraBishnoi29~~
    - [x]  DocLink.tsx @Master7130 #7780 
    - [x]  DocsNav.tsx @wackerow #7821
    - [x]  EnergyConsumptionChart.tsx @wackerow #7825
    - [x]  EthVideo.tsx @MahendraBishnoi29 #7785
    - [x]  EventCard.tsx @LuisUrrutia #8152
    - [x]  ExpandableCard.tsx @jb-0 #8572
    - [x]  ExpandableInfo.tsx @TylerAPfledderer #8224
    - [x]  FeedbackCard.tsx @wackerow #7906
    - [x]  FeedbackWidget.tsx @wackerow #7906
    - [x]  Footer.tsx @TylerAPfledderer #8506
    - [x]  GhostCard.tsx @douglasmakey #8413
    - [x] #8049 hacktoberfest
    - [x]  HorizontalCard.tsx @ameeetgaikwad #7893
    - [x]  ImageCard.tsx @ImMiguelP #7959
    - [x]  InfoBanner.tsx @ImMiguelP #7929
    - [x]  Layer2ProductCard.tsx @ImMiguelP #8007
    - [x]  Leaderboard.tsx @ImMiguelP #8041
    - [x]  Link.tsx @pettinarip #7438
    - [x]  Logo.tsx @laurentlucian #7872
    - [x]  MarkdownTable.tsx @ImMiguelP #8061
    - [x]  MatomoOptOut.tsx @ImMiguelP #8042
    - [x]  MeetupList.tsx @ImMiguelP #8043
    - [x]  MergeInfographic.tsx @victorpatru #8246
    - [x]  Morpher.tsx @laurentlucian #7887
    - [x]  NakedButton.tsx @wackerow #9519
    - [x]  OrderedList.tsx @TylerAPfledderer #8175
    - [x]  Pill.tsx @vdusart #8501
    - [x] ~PreMergeBanner.tsx (deprecated as of The Merge)~
    - [x]  ProductList.tsx @Master7130 #8414
    - [x]  ~~RandomAppList.tsx @AliTechGeek52~~
    - [x] #8050 hacktoberfest #8081
    - [x]  RollupProductDevDoc.tsx @TylerAPfledderer #8248
    - [x]  SectionNav.tsx @Master7130 #7978
    - [x]  SkipLink.tsx @MahendraBishnoi29 #8602
    - [x] #8051 hacktoberfest
    - [x]  SocialListItem.tsx @Gift-Stack #7990
    - [x]  StablecoinBoxGrid.tsx @shariqanwar20 #8201
    - [x]  StatErrorMessage.tsx @therealharpaljadeja #8199
    - [x]  StatLoadingMessage.tsx @therealharpaljadeja #8199
    - [x]  Tag.tsx @hannsu #7735
    - [x]  TitleCardList.tsx @shubham16598 #8067
    - [x] #8052 hacktoberfest
    - [x]  TutorialTags.tsx @TylerAPfledderer #8774
    - [x]  UpgradeBannerNotification.tsx @Mahmadabid #8189
    - [x]  UpgradeStatus.tsx @jb-0 #8195
    - [x]  UpgradeTableOfContents.tsx @minimalsm PR: #7725
    - [x]  VisuallyHidden.tsx @minimalsm PR: #7724
    - [x]  YouTube.tsx @minimalsm PR: #7723
</details>

**Comment by MahendraBishnoi29** [comment]
can i contribute?

**Comment by SNikhill** [comment]
Is there going to be a list of the components that are to be ported over?

**Comment by pettinarip** [comment]
> Is there going to be a list of the components that are to be ported over?

Yes! we are preparing the ground for that. I'll update this same issue with the list of files soon (~this week) & will let you know.

**Comment by SNikhill** [comment]
@pettinarip 
May I please have the 4 A's?
![image](https://user-images.githubusercontent.com/51415616/188634139-4a4c1105-ce14-4aa3-b253-368a10c44fbe.png)

**Comment by Mousticke** [comment]
@pettinarip 
Let's go for the B's
-[ ] BannerNotification.tsx
-[ ] BoxGrid.tsx
-[ ] Breadcrumbs.tsx
-[ ] BugBountyCards.tsx
-[ ] ButtonLink.tsx

**Comment by pettinarip** [comment]
wohooo! @SNikhill assigned! @Mousticke assigned as well (`ButtonLink` was already migrated, I've removed it from the list).

@vdusart assigned as well the C's

Thanks all! 🚀

**Comment by ameeetgaikwad** [comment]
Can I contribute?

**Comment by minimalsm** [comment]
Hey @ameeetgaikwad, thanks for offering to help. We'd love your help on this :-) Is there a specific component you'd be interested in starting with?

**Comment by EatCrypto** [comment]
Can I contribute on these E-components?

- [ ]  EnergyConsumptionChart.tsx
- [ ]  EthVideo.tsx
- [ ]  EventCard.tsx
- [ ]  ExpandableCard.tsx
- [ ]  ExpandableInfo.tsx

**Comment by pettinarip** [comment]
Hey @EatCrypto thanks for reaching out and trying to help us with this migration. We are only assigning multiple files to old contributors for now.

I've assigned `EnergyConsumptionChart.tsx` to you. Once you finish with that one, we can assign you another one ✌🏼

**Comment by EatCrypto** [comment]
> Hey @EatCrypto thanks for reaching out and trying to help us with this migration. We are only assigning multiple files to old contributors for now.
> 
> I've assigned `EnergyConsumptionChart.tsx` to you. Once you finish with that one, we can assign you another one ✌🏼

Sounds good. Thanks.

**Comment by pettinarip** [comment]
> > Hey @ameeetgaikwad, thanks for offering to help. We'd love your help on this :-) Is there a specific component you'd be interested in starting with?
> 
> Hey @minimalsm I recently learnt the basic of react. Please refer me a component which you see fit.

Hey @ameeetgaikwad awesome! I've assigned you the `HorizontalCard.tsx` file, which is not a difficult one.

LMK if you need any help or if you have any questions in the process.

**Comment by marcellamalune** [comment]
Hi! Can I contribute? The checkbox or anything else would be fine 😊

**Comment by minimalsm** [comment]
Hey @marcellamalune, thanks for the help 💪 I've assigned `Checkbox.tsx` to you. 

Any questions feel free to ask 👍

**Comment by minimalsm** [comment]
> can i contribute?

Hey @MahendraBishnoi29, just calling out this has opened up, if you're still interested 💪

**Comment by hannsu** [comment]
Hi! I can help with the Link and Logo component.

**Comment by minimalsm** [comment]
Thanks @hannsu ❤️❤️❤️ The limit is kinda arbitrary, we just don't want first time contributors biting off too much and getting discouraged. I'll add you to the tag component. Feel free to pick up the other after if it's available.

**Comment by MahendraBishnoi29** [comment]
hey guyss i'm confused, like all i have to do is the refactor the site with Chakra UI?

**Comment by pettinarip** [comment]
> hey guyss i'm confused, like all i have to do is refactor the site with Chakra UI?

Basically, yes. The scope of this epic is replacing the `@emotion` styled-components with Chakra UI components.

Once we have all the UI components with Chakra we will start adopting the Design System #6284 that our designers are currently working on.

**Comment by LuisUrrutia** [comment]
Is it on the scope to maintain the current design? If a chakra component looks way different from the current style, should we stick to the chakra design, or do we have to do all the modifications to match the current style?

**Comment by Master7130** [comment]
Hi, can I work on refactoring DocLink.tsx?

**Comment by pettinarip** [comment]
> Hi, can I work on refactoring DocLink.tsx?

Assigned @Master7130, thanks!

**Comment by MahendraBishnoi29** [comment]
I want to work on `EthVideo.tsx `   🚀

**Comment by MahendraBishnoi29** [comment]
I want to work on `EthVideo.tsx` 🛠

**Comment by pettinarip** [comment]
Assigned @MahendraBishnoi29 👍🏼 ty

**Comment by MahendraBishnoi29** [comment]
> Assigned @MahendraBishnoi29 👍🏼 ty

hey @pettinarip where's this video?

**Comment by pettinarip** [comment]
> > Assigned @MahendraBishnoi29 👍🏼 ty
> 
> hey @pettinarip where's this video?

You can find it in `src/pages-conditional/eth.tsx` which is the following page: https://ethereum.org/en/eth/

![image](https://user-images.githubusercontent.com/468158/189162012-9b8b5cc3-814a-4bd1-b3fa-d634fc1b27c3.png)

**Comment by MahendraBishnoi29** [comment]
@pettinarip i cloned ethereum org site locally but it get stucked here 

<img width="889" alt="Screenshot 2022-09-09 095259" src="https://user-images.githubusercontent.com/74294202/189271644-dec391a4-7484-4e0c-b87b-374a0cb8e2f1.png">

**Comment by MahendraBishnoi29** [comment]
> @pettinarip i cloned ethereum org site locally but it get stucked here
> 
> <img alt="Screenshot 2022-09-09 095259" width="889" src="https://user-images.githubusercontent.com/74294202/189271644-dec391a4-7484-4e0c-b87b-374a0cb8e2f1.png">

and then it gave me a infinite error list in terminal

**Comment by pettinarip** [comment]
Hey @MahendraBishnoi29 by default the app is building all the languages the site has (which is a lot) and it can take a while to generate all those nodes that the log is describing.

Do the following:
- Duplicate the `.env.example` file and rename it as `.env`, at the root of the app
- Update `GATSBY_BUILD_LANGS=en` to only build one lang (english only in this case)

With that, you should have a faster build. If you face more issues, ping me on Discord and I could take a closer look at those errors you are have.

**Comment by MahendraBishnoi29** [comment]
> Hey @MahendraBishnoi29 by default the app is building all the languages the site has (which is a lot) and it can take a while to generate all those nodes that the log is describing.
> 
> Do the following:
> 
> * Duplicate the `.env.example` file and rename it as `.env`, at the root of the app
> * Update `GATSBY_BUILD_LANGS=en` to only build one lang (english only in this case)
> 
> With that, you should have a faster build. If you face more issues, ping me on Discord and I could take a closer look at those errors you are have.

discord id?

**Comment by pettinarip** [comment]
> discord id?

pablop#2353

**Comment by MahendraBishnoi29** [comment]
> > discord id?
> 
> pablop#2353

couldn't find you in ethereum discord server but i've sent you friend request through direct messages.

**Comment by ameeetgaikwad** [comment]
Can someone help me with #7783 ?

**Comment by ameeetgaikwad** [comment]
@pettinarip #7784

**Comment by ameeetgaikwad** [comment]
@pettinarip check out my pull request on `HorizontalCard`. #7784

**Comment by AntonioSalazar** [comment]
Hey! I would like to help which file I can work on?

**Comment by ameeetgaikwad** [comment]
#7784

**Comment by minimalsm** [comment]
Hey @AntonioSalazar :-) thanks for offering to help. You can pick up any of the components listed above that aren't already assigned. 

Any suggestions on a good first one @pettinarip?

**Comment by derajohnson** [comment]
Hi. I would like to work on the footer.

**Comment by MahendraBishnoi29** [comment]
@minimalsm can you please review my PR?

**Comment by pettinarip** [comment]
Hey @AntonioSalazar I'm assigning `Pill.tsx` to you 💪🏼 should be pretty straight forward. Thanks for the help!

**Comment by pettinarip** [comment]
> Hi. I would like to work on the footer.

Assigned @derajohnson! 🙏🏼 ty

**Comment by frankiefab100** [comment]
Hello, I will like to work on `CopyToClipboard`

**Comment by pettinarip** [comment]
> Hello, I will like to work on `CopyToClipboard`

Awesome @frankiefab100 I've assigned it to you, thanks for the help ❤️

**Comment by Gift-Stack** [comment]
I’d like to work on these components;

SocialListItem.tsx
StablecoinBoxGrid.tsx
StatErrorMessage.tsx
StatLoadingMessage.tsx

**Comment by pettinarip** [comment]
Hey @Gift-Stack thanks for the help! I'm just assigning `SocialListItem.tsx` for now. Once we finish with that one we can assign the other ones.

**Comment by MahendraBishnoi29** [comment]
hey @pettinarip can you please review my PR?

**Comment by laurentlucian** [comment]
hey @pettinarip, I picked `Logo` component as my first contribution and I'd like to migrate `Morpher` next

**Comment by ImMiguelP** [comment]
i will like to contribute with `ImageCard.tsx` and `InfoBanner.tsx ` @pettinarip

**Comment by pettinarip** [comment]
Files assigned guys @MahendraBishnoi29 @laurentlucian @ImMiguelP ✌🏼 thanks!

**Comment by ameeetgaikwad** [comment]
Hey @pettinarip review my pr #7893

**Comment by ameeetgaikwad** [comment]
Check out #7893

**Comment by ameeetgaikwad** [comment]
#7893

**Comment by Master7130** [comment]
Can I work on SectionNav.tsx?

**Comment by pettinarip** [comment]
> Can I work on SectionNav.tsx?

Sure, I've assigned that one to you @Master7130 ty

**Comment by Master7130** [comment]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/85327930/191633252-3d0b85bd-8045-4e5c-a4d5-d1cf845e2d1e.png">
Anybody know how to fix this error? It's happening when I try to go to "http://localhost:8000/en/developers/docs/intro-to-ethereum/."

**Comment by MahendraBishnoi29** [comment]
> <img width="1079" alt="image" src="https://user-images.githubusercontent.com/85327930/191633252-3d0b85bd-8045-4e5c-a4d5-d1cf845e2d1e.png">
> Anybody know how to fix this error? It's happening when I try to go to "http://localhost:8000/en/developers/docs/intro-to-ethereum/"

umm i just hard refresh the page and it works 🙂 and also you can pull latest commits and merge them.

**Comment by Master7130** [comment]
> 
> umm i just hard refresh the page and it works 🙂 and also you can pull latest commits and merge them.

Didn't work so I just cloned the repo again and it worked fine. Thanks for trying to help though.

**Comment by LuisUrrutia** [comment]
Hi there, I would like to take `CodeModal.tsx`

**Comment by pettinarip** [comment]
> Hi there, I would like to take `CodeModal.tsx`

Assigned @LuisUrrutia 💪🏼

**Comment by LuisUrrutia** [comment]
> > Hi there, I would like to take `CodeModal.tsx`
> 
> Assigned @LuisUrrutia 💪🏼

Already done, so I'm going to take `DataProductCard.tsx`

**Comment by shubham16598** [comment]
Hi there,
I'd like to contribute to this task as well, can I take:
TitleCardList.tsx
TranslationBanner.tsx
TutorialTags.tsx
Thanks

**Comment by pettinarip** [comment]
Assigned @LuisUrrutia

**Comment by pettinarip** [comment]
> Hi there, I'd like to contribute to this task as well, can I take: TitleCardList.tsx TranslationBanner.tsx TutorialTags.tsx Thanks

Hi @shubham16598 I'm assigning just `TitleCardList` for now. Once we finish with that one I can assign the others 💪🏼 thanks!

**Comment by LuisUrrutia** [comment]
My PR are in review. Meanwhile, I'm going to ask for another component: `EventCard.tsx`

**Comment by pettinarip** [comment]
> My PR are in review. Meanwhile, I'm going to ask for another component: `EventCard.tsx`

Awesome, assigned!

**Comment by Master7130** [comment]
Can I work on ProductList.tsx?

**Comment by LuisUrrutia** [comment]
@pettinarip `EventCard.tsx` is also done. I will ask for `ExpandableCard.tsx` now, and a friend (@douglasmakey) wants to take `GhostCard.tsx`. For some weird reason, he can't comment on this issue, and we are already in touch with the GitHub Support team, but it would be great if you could assign that component to him.

**Comment by pettinarip** [comment]
@Master7130 @LuisUrrutia assigned! thanks

**Comment by nikolovlazar** [comment]
Hi @pettinarip! I'm Lazar, a Chakra UI core member. I noticed the Notion page with the research summary is available only to EF org members. Would love to have a chance to check out that page, if that's possible. Also, would you or anyone else from the foundation be interested in creating a case study for our website?

**Comment by segunadebayo** [comment]
Creator of Chakra UI here. Excited to see this migration effort!

Happy to help or provide more guidance here if needed. As @nikolovlazar mentioned, we're curious to learn about the decision points that led to choosing Chakra UI.

**Comment by Khadeeejah** [comment]
HI are there any components left to contribute to, i would love to contribute

**Comment by samajammin** [comment]
Hey @nikolovlazar @segunadebayo - glad & flattered to see your interest! Also thank you for creating/contributing to Chakra 😄 

Not sure how our research doc became private. I've made it public again:
https://www.notion.so/efdn/Research-options-and-select-UI-library-babae0a343e24c92be0d6bd486e35c1c

Please let us know if you have any thoughts or questions!

**Comment by TylerAPfledderer** [comment]
@pettinarip I'd like to start with the `OrderedList` please. This is exciting stuff! 😄

**Comment by jb-0** [comment]
I'd be happy to help out, I could start with `TutorialTags.tsx`. I will wait to hear back before making a start.

Thanks

**Comment by pettinarip** [comment]
@nikolovlazar @segunadebayo thanks for the amazing work on ChakraUI and for reaching out!

Just saw also that you've added eth.org to the [Chakra showcase](https://chakra-ui.com/community/showcase). Thats amazing! 💪🏼 

Same as @samajammin, curious to know how we could help out with the case study.

**Comment by pettinarip** [comment]
> @pettinarip I'd like to start with the `OrderedList` and `ExpandableInfo` please. This is exciting stuff! smile
> 
> Edit: I'm already near the end to submit a PR for `OrderedList` sweat_smile

Cool! thanks for that @TylerAPfledderer! Was going to tell you that `OrderedList` should probably be completely replaced by the [native Chakra `OrderedList`](https://chakra-ui.com/docs/components/list/usage#ordered-list).

We can discuss this in more detail on your PR. I'm assigning those two files to you.

**Comment by pettinarip** [comment]
> I'd be happy to help out, I could start with `TutorialTags.tsx`. I will wait to hear back before making a start.
> 
> Thanks

Hey @jb-0 thanks for helping us here. Just realized that `TutorialTags.tsx` depends on `Pill.tsx` (which is already assigned).

Would you like to work on a different file? or I could assign one to you

**Comment by jb-0** [comment]
> > I'd be happy to help out, I could start with `TutorialTags.tsx`. I will wait to hear back before making a start.
> > 
> > Thanks
> 
> Hey @jb-0 thanks for helping us here. Just realized that `TutorialTags.tsx` depends on `Pill.tsx` (which is already assigned).
> 
> Would you like to work on a different file? or I could assign one to you

Sure, feel free to assign anything to me.

**Comment by pettinarip** [comment]
Cool, I've assigned `UpgradeStatus.tsx` to you @jb-0 ty!

**Comment by Mahmadabid** [comment]
I want to contribute

**Comment by shariqanwar20** [comment]
Can I please have these
![Screenshot_20221005-090843_Chrome](https://user-images.githubusercontent.com/61353122/193979655-d0ab23ea-d59f-4f2b-bf31-56709dd08973.jpg)

**Comment by Mahmadabid** [comment]
statLoadingMessage.tsx
statErrorMessage.tsx
Can I have this?

**Comment by Mahmadabid** [comment]
Can I contribute?
RandomAppList.tsx
UpgradeBannerNotification.tsx

**Comment by AliTechGeek52** [comment]
@pettinarip Can I take RandomAppList.tsx ?

**Comment by pettinarip** [comment]
@shariqanwar20 Thanks! I'm assigning `StablecoinBoxGrid.tsx` for now. Once we are done with that one I can assign the others.

**Comment by TylerAPfledderer** [comment]
@pettinarip I checked out `PageMetaData`. I don't believe it needs the conversion because it is using logic from Gatsby and reach router with no visual components. 

Is there anything from Chakra you would like to see in addition to what's there?

**Comment by victorpatru** [comment]
Hey @pettinarip. I would love to assigned to the `MergeInfographic.tsx` component!

**Comment by shubham16598** [comment]
Hey, @pettinarip Can I get another component assigned? I have raised a PR for TitleCardList.tsx  https://github.com/ethereum/ethereum-org-website/pull/8067

**Comment by therealharpaljadeja** [comment]
hey, @pettinarip please assign me a file.

**Comment by pettinarip** [comment]
Thanks for noting that @TylerAPfledderer. Yea, make sense to leave it as it is. You could work on `RollupProductDevDoc.tsx`, I'm assigning that one to you.

`RollupProductDevDoc.tsx` => @TylerAPfledderer
`MergeInfographic.tsx` => @victorpatru
`StatErrorMessage.tsx` => @shubham16598
`StatLoadingMessage.tsx` => @therealharpaljadeja

Thanks all of you guys!

**Comment by TylerAPfledderer** [comment]
> I'll take `PageMetadata.tsx` as that looks like the only one still open.
> 
> Thanks!

Hey @psparacino ! 😄 

I had commented previously that this component probably does not need migration, and @pettinarip responded above. :)

**Comment by timi-codes** [comment]
@pettinarip I'm happy to work any other components that comes up.

**Comment by ameeetgaikwad** [comment]
hello, can you assign me some beginner level task? @pettinarip

**Comment by Khadeeejah** [comment]
Hello @pettinarip  kindly assign a task to me thanks

**Comment by Marcelixoo** [comment]
It seems that everything was already taken, so I'm happy to support any peer with work in progress or maybe take on further work on unlisted components.

**Comment by AliTechGeek52** [comment]
Hi @Marcelixoo you can help me in work ( I am working on this component RandomAppList yet ).

**Comment by Marcelixoo** [comment]
> Hi @Marcelixoo you can help me in work ( I am working on this component RandomAppList yet ).

Hey @AliTechGeek52, how do you want to collaborate on that? Do you already have a fork that I can start working on? Or do you prefer to work on it together, i.e. via Discord?

**Comment by wackerow** [comment]
Hey @pettinarip, noting that there seems to be a known bug with Chakra-UI when hovering over a `disabled` button

Existing issue with potential workaround patch: https://github.com/chakra-ui/chakra-ui/discussions/5211

We came across this while working on the Learning Quiz widget. 
<img width="291" alt="image" src="https://user-images.githubusercontent.com/54227730/196556288-a3a17caf-7a02-47c4-aa3b-9615c278dbfb.png">

I did not want to mess with this in that PR to avoid scope creep, but I wanted to make note of this as we should try to patch this for our disabled buttons.

**Comment by pettinarip** [comment]
Thanks @wackerow will keep this in mind. I've created an issue to keep track of it #8295.

**Comment by pettinarip** [comment]
Hey @TylerAPfledderer that is awesome! For sure, any input on the subject is always welcome. Feel free to review that PR and leave suggestions or open a new issue/PR to improve other things 💯

**Comment by abdulmoizlakhani** [comment]
Hi, I need a component to work on.

**Comment by pettinarip** [comment]
@SNikhill @Mousticke @MahendraBishnoi29 @LuisUrrutia @derajohnson @douglasmakey @AntonioSalazar @AliTechGeek52

Calling out people who have files assigned to them and that **don’t** have a PR created yet. I wanted to check if you are still interested and are planning on migrating them in the short term.

If you are not planning on that anymore, we can reassign to other people that may want to work on them.

**I’d assume that you’re not working on them if I don't receive a reply in the next couple of days.**

Thanks in advance 🐼

**Comment by Master7130** [comment]
I'll have a PR in hopefully tomorrow for ProductList.tsx.

**Comment by MahendraBishnoi29** [comment]
> @SNikhill @Mousticke @MahendraBishnoi29 @LuisUrrutia @derajohnson @douglasmakey @AntonioSalazar @AliTechGeek52
> 
> Calling out people who have files assigned to them and that **don’t** have a PR created yet. I wanted to check if you are still interested and are planning on migrating them in the short term.
> 
> If you are not planning on that anymore, we can reassign to other people that may want to work on them.
> 
> **I’d assume that you’re not working on them if I don't receive a reply in the next couple of days.**
> 
> Thanks in advance 🐼 

I'm working on my assigned components 💪🏻

**Comment by derajohnson** [comment]
> @SNikhill @Mousticke @MahendraBishnoi29 @LuisUrrutia @derajohnson @douglasmakey @AntonioSalazar @AliTechGeek52
> 
> Calling out people who have files assigned to them and that **don’t** have a PR created yet. I wanted to check if you are still interested and are planning on migrating them in the short term.
> 
> If you are not planning on that anymore, we can reassign to other people that may want to work on them.
> 
> **I’d assume that you’re not working on them if I don't receive a reply in the next couple of days.**
> 
> Thanks in advance 🐼

Hi, I’m sorry for not being able to work on my component. I haven’t been able to run it locally. I always get an error so yes, you can reassign my component.

**Comment by SNikhill** [comment]
> @SNikhill @Mousticke @MahendraBishnoi29 @LuisUrrutia @derajohnson @douglasmakey @AntonioSalazar @AliTechGeek52
> 
> Calling out people who have files assigned to them and that **don’t** have a PR created yet. I wanted to check if you are still interested and are planning on migrating them in the short term.
> 
> If you are not planning on that anymore, we can reassign to other people that may want to work on them.
> 
> **I’d assume that you’re not working on them if I don't receive a reply in the next couple of days.**
> 
> Thanks in advance panda_face

Greetings @pettinarip, 
I have been slightly engaged with some personal stuff.
Yes, I am still interested in working on the same and I shall create some PR(s) in the coming days.

Apologies for the delay.

**Comment by AliTechGeek52** [comment]
> @SNikhill @Mousticke @MahendraBishnoi29 @LuisUrrutia @derajohnson @douglasmakey @AntonioSalazar @AliTechGeek52
> 
> Calling out people who have files assigned to them and that **don’t** have a PR created yet. I wanted to check if you are still interested and are planning on migrating them in the short term.
> 
> If you are not planning on that anymore, we can reassign to other people that may want to work on them.
> 
> **I’d assume that you’re not working on them if I don't receive a reply in the next couple of days.**
> 
> Thanks in advance 🐼

Hello, @pettinarip I am working on the component and will create PR once it will be fully done. Sorry for the late reply.

**Comment by TylerAPfledderer** [comment]
> > @SNikhill @Mousticke @MahendraBishnoi29 @LuisUrrutia @derajohnson @douglasmakey @AntonioSalazar @AliTechGeek52
> > Calling out people who have files assigned to them and that **don’t** have a PR created yet. I wanted to check if you are still interested and are planning on migrating them in the short term.
> > If you are not planning on that anymore, we can reassign to other people that may want to work on them.
> > **I’d assume that you’re not working on them if I don't receive a reply in the next couple of days.**
> > Thanks in advance 🐼
> 
> Hi, I’m sorry for not being able to work on my component. I haven’t been able to run it locally. I always get an error so yes, you can reassign my component.

@pettinarip if this is to be reassigned (`Footer.tsx`), I'm happy to take it over!

**Comment by pettinarip** [comment]
Assigned @TylerAPfledderer thanks!

=====
To everyone, there are a few unassigned files. For those who want to pick one, here is the list:
- BoxGrid.tsx
- Breadcrumbs.tsx
- BugBountyCards.tsx
- ExpandableCard.tsx
- Pill.tsx

**Comment by Master7130** [comment]
Can I work on BoxGrid.tsx?

**Comment by jb-0** [comment]
@pettinarip - I'm happy to pick up another, can take a look on the weekend. No preference.

**Comment by Marcelixoo** [comment]
Hey @pettinarip, can I work on `BugBountyCards.tsx`?

**Comment by pettinarip** [comment]
@Master7130 @jb-0 @Marcelixoo thanks!

**Comment by vdusart** [comment]
@pettinarip Can I work on the `Pill.tsx` component ?

**Comment by pettinarip** [comment]
Done @vdusart! ty

**Comment by shariqanwar20** [comment]
@pettinarip can you assign me another component. No preference

**Comment by pettinarip** [comment]
I've assigned `BoxGrid.tsx` to you @shariqanwar20 ty!

**Comment by SNikhill** [comment]
@pettinarip 

The `Accordion.tsx` contains: StableCoinAccordion and apparently, this component is not being used.

Another StablecoinAccordion.tsx component exists and is being used in the Stablecoins page.

**Comment by psparacino** [comment]
@pettinarip im free to work on one if there are any remaining👍

**Comment by TylerAPfledderer** [comment]
> @pettinarip
> 
> The `Accordion.tsx` contains: StableCoinAccordion and apparently, this component is not being used.
> 
> Another StablecoinAccordion.tsx component exists and is being used in the Stablecoins page.

@SNikhill @pettinarip I wonder if this component was supposed to exist? See PR #1938. It looks to have been added, but never implemented.

**Comment by pettinarip** [comment]
Good point @SNikhill @TylerAPfledderer. I think we can delete it. Would appreciate @SNikhill if you can create a PR to do that.

**Comment by pettinarip** [comment]
@psparacino all the files are assigned right now. Will let you know when we have more files to migrate :)

**Comment by pettinarip** [comment]
Assigning `TutorialTags.tsx` to you @psparacino.

**Comment by marcellamalune** [comment]
@pettinarip I can work on another component if something is pending 😄

**Comment by rishisundar** [comment]
Hey, can I work on something? Don't have any preference. Would love to contribute!

**Comment by SNikhill** [comment]
@pettinarip 

I have made the suggested changes to the ActionCard in #8009.
Sorry for the delay.

**Comment by pettinarip** [comment]
Thanks @SNikhill!

Hey @rishisundar we've just created a new GH issue to start migrating our pages and templates, check it out! #9353

**Comment by TylerAPfledderer** [comment]
@MahendraBishnoi29 @AliTechGeek52 Hey there! 👋

I'm helping out with the migrations here. I see that there are components still assigned to you that do not appear to have PRs up.

`Dismissable` and `RandomAppList`, respectively.

Are you still able to complete these components, or need some assistance? 😀

**Comment by MahendraBishnoi29** [comment]
> @MahendraBishnoi29 @AliTechGeek52 Hey there! 👋
> 
> I'm helping out with the migrations here. I see that there are components still assigned to you that do not appear to have PRs up.
> 
> `Dismissable` and `RandomAppList`, respectively.
> 
> Are you still able to complete these components, or need some assistance? 😀

hey, @TylerAPfledderer thanks for helping here. so I've discussed with @pettinarip that  `DismissableCard` is not in use currently so I haven't made a PR yet but if you still want me to make a PR I'll do it 😀

**Comment by TylerAPfledderer** [comment]
@MahendraBishnoi29 No need! That is Pablo's call to roll with 🤘

**Comment by MahendraBishnoi29** [comment]
> 

appreciate your help @TylerAPfledderer ♥

**Comment by pettinarip** [comment]
🚀 🚀 🚀 

Thanks everyone!! closing now. Amazing community work :) 🕺🏼 

🚀 🚀 🚀
