### ISSUE TITLE
Epic: Implement HEART framework

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#7205]
**Epic description**

As part of our Q3 roadmap (#7166), this initiative is to apply the HEART framework to contributors of the Translation Program, thinking about all aspects of this contributor funnel (Happiness, Engagement, Adoption, Retention, and Task success). The scope will include implementing the framework, pulling in data to support it, and coming up with key takeaways. 

We’ll use the results to determine high-impact opportunities to improve and will guide our operational and product priorities next quarter.

With the translation program as a testing ground, we’ll also consider applying the HEART framework more broadly across all our contributor funnels.

**Goals**

- Think about all elements of the HEART framework and how they relate to ethereum.org translators
- Collect takeaways and potential improvements to the translators’ experience
- Turn this into a structured way of analyzing contributor experience in the Translation Program and throughout the website

**Checklist**

- [x] Happiness analysis
- [x] Engagement analysis
- [x] Adoption analysis
- [x] Retention analysis
- [x] Task success analysis
- [x] Happiness takeaways
- [x] Engagement takeaways
- [x] Adoption takeaways
- [x] Retention takeaways
- [x] Task success takeaways
- [x] HEART framework retrospective
