### ISSUE TITLE
Epic: Revamp the Translation Program page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#7206]
**Epic description**

The [Translation Program page](https://ethereum.org/en/contributing/translation-program/) is dedicated to the ethereum.org Translation Program and contains a lot of information on what the program is, how to get involved, supplementary resources, and other key information. It has been constantly growing in size and we’ve added a lot of information that could be important for translators and make contributing to the Translation Program easier.

As part of our Q3 roadmap (#7166), we want to review the information architecture and user flow on the page, break out some sections into dedicated subpages, create subpages for other web properties that we are translating (specifically the [Staking Launchpad](https://launchpad.ethereum.org/en/) and the [EF blog](https://blog.ethereum.org/)), and review & update all of the information on the page.

**Goals**

- Review IA and user flow on the page
- Reduce the amount of text and create subpages for most sections
- Review and update all the information on the page

**Checklist**

- [x] Review IA and user flow
- [x] Create Translation Program hub
- [x] Create Blog translations subpage
- [x] Create Launchpad translations subpage
- [x] Create How to translate subpage
- [x] Create Mission & vision subpage
- [x] Add non-English pageview stats
- [x] Review & update all content
