### ISSUE TITLE
Epic: 🗣️ User insights

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#7226]
Last quarter we shipped a new feedback widget (https://github.com/ethereum/ethereum-org-website/issues/6252) integrated with custom surveys across all pages on [ethereum.org](http://ethereum.org/) and started collecting data.

This [quarter](https://github.com/ethereum/ethereum-org-website/issues/7166) we will focus on: 

- [x] - Validation and analysis of your responses to formulate useful insights to improve ethereum.org
- [x] - We’ll build data studio reports to help with the analysis of data
- [x] - We’ll consider how we might publish these research findings as a public good to the Ethereum product community. 
- [x] - We will also use this data to influence our content strategy decisions and priorities.
- [x] - Last but not least we will also improve the visibility of the feedback widget on the desktop: https://github.com/ethereum/ethereum-org-website/issues/8298 **(calling the community to help on this ticket)**

**Want to contribute?**
Want to get involved? Join the conversation in our [#design Discord channel](https://discord.gg/bKycYhVUwV). We would love to ideate and discuss our approach or help with the data analysis and insights generation. Furthermore, we would appreciate help with building the data studio dashboards.

**Comment by konopkja** [comment]
Update: performed user testing (7 participants) at ETHCC in Paris. Scope: Find wallet page and What is Ethereum page.

**Comment by samajammin** [comment]
Noting this epic is part of our Q3 roadmap: https://github.com/ethereum/ethereum-org-website/issues/7166
