### ISSUE TITLE
Epic: Wallet upgrades 💰

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#7250]
**Is your feature request related to a problem? Please describe.**

In Q2 the [Find Wallet page](https://ethereum.org/wallets/find-wallet) was revamped (https://github.com/ethereum/ethereum-org-website/issues/6274). While this was a large release that introduced substantial changes to the data gathered on wallets and how users can filter and find a wallet, there are still some remaining features and clean-up items that would improve the find wallet page. In Q3 the find wallets page will be iterated on to introduce additional improvements that were scoped out of the initial release.

There is also some cleanup around ethereum.org that needs to be done now that wallet data is being sourced from a new file. In Q3 this cleanup work will be addressed.

This quarter we will tackle:
- [x] Use radio toggle in persona panel (abandoned)
- [x] [Remove wallet lists from /wallets page](https://github.com/ethereum/ethereum-org-website/pull/7185)
- [x] [Remove wallets.csv](https://github.com/ethereum/ethereum-org-website/pull/7318)
- [x] Confirm the definition of wallets (closed after reviewing /wallets page)
- [x] Backfill wallet data (closed after adding ledger and trezor, have a good set to start)
- [x] [Close filter panel on mobile when tapping outside filter sidebar](https://github.com/ethereum/ethereum-org-website/pull/8258)
- [x] [Rename EIP-1559 to "Gas fee optimization"](https://github.com/ethereum/ethereum-org-website/pull/7319)
- [x] Browser wallet support
- [x] [Update "types of wallets" on the /wallets page](https://github.com/ethereum/ethereum-org-website/pull/7320)
- [x] [Consolidate wallet data (for /get-eth & /find-wallet)](https://github.com/ethereum/ethereum-org-website/pull/7367)
- [ ] URL parameters for pre-applied filters
- [ ] Show selected/applied filters
- [ ] Expand custodial definitions to include semi-custodial/MPC wallet
- [ ] Animate filter panel on table and mobile views
- [ ] build ranking algorithm for wallets
- [x] Set up the find wallet page for translation (#7373)
- [ ] Replace hero image on /wallets page
- [ ] Introduce a multichain user persona and data
- [ ] Investigate regionalized buy crypto data

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
> Rename EIP-1559 to "Gas fee optimization"

Are these the same thing? To me:

- EIP-1559 is gas optimisation at the protocol level
-  But you can also have gas optimisation at the wallet level (controlling your own gas limit)

**Comment by corwintines** [comment]
I view the second part to be more gas fee customization. For reference, we pulled this name from the discussion in this issue: https://github.com/ethereum/ethereum-org-website/issues/2715

Happy to discuss a better name than 'Gas fee optimization' though. Any suggestions?

**Comment by samajammin** [comment]
Noting this epic is part of our Q3 roadmap: https://github.com/ethereum/ethereum-org-website/issues/7166

**Comment by samajammin** [comment]
> Rename EIP-1559 to "Gas fee optimization"

Encourage more workshopping of the terminology we want to use for EIP-1559 type 2 txs but for now I agree with @corwintines that "Gas fee optimization" is the best approach. As he mentioned, "Gas fee customization" is the ability for users to customize their txs, such as explicitly setting priority fee, max fee, gas limit, etc.

**Comment by corwintines** [comment]
You can find a full summary of Q3 2022 above, but in Q3 we knocked out some cleanup work this quarter to remove unused data in the codebase for wallets and added [~10 new wallets](https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aissue+label%3A%22wallet+%3Apurse%3A%22+is%3Aclosed) to give users more options, particularly for hardware wallets. Work will be carrying over into Q4, especially on UX improvements, which we've created issues for Hacktoberfest to give the community ways to contribute.

Issues have been opened for the outstanding items above so that we can close this epic.

https://github.com/ethereum/ethereum-org-website/issues/9209
https://github.com/ethereum/ethereum-org-website/issues/9210
https://github.com/ethereum/ethereum-org-website/issues/9211
https://github.com/ethereum/ethereum-org-website/issues/8172
https://github.com/ethereum/ethereum-org-website/issues/8169
https://github.com/ethereum/ethereum-org-website/issues/8167
