### ISSUE TITLE
Epic: Wallet resources 💰

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#7251]
As we expand resources for the wallet section of ethereum.org, there is an opportunity to expand on content around the different types of accounts and wallets for the https://ethereum.org/wallets page. As part of this epic, five new subpages will be created going into detail on the different kinds of accounts (EOA, contract), and their respective wallet interfaces they can use (private-key wallet, smart contract wallet, and MPC wallets). 

This quarter we will focus on:
- [ ] Externally Owned Account (EOA) research
- [ ] EOA page
- [ ] Contract account research
- [ ] Contract account page
- [ ] Private-key wallet research
- [ ] Private-key wallet page
- [ ] Smart contract wallet research
- [ ] Smart contract wallet page
- [ ] MPC wallet research
- [ ] MPC wallet page

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR. Some ways to help on this epic include:
- Suggesting resources for the above topics
- Contributing content for the above topics

**Comment by samajammin** [comment]
Noting this epic is part of our Q3 roadmap: #7166

**Comment by samajammin** [comment]
Unfortunately we didn't get to this epic in Q3. 

Any thoughts on how to proceed?
- @corwintines could we create standalone content issues to cover the given topics? Not sure if we have any research we could include or page outlines that we could open to the community to contribute to? Maybe @emmanuel-awosika might be interested?
- @minimalsm otherwise maybe we loop this into content strategy work (#7240) somehow?

**Comment by emmanuel-awosika** [comment]
> Unfortunately we didn't get to this epic in Q3.
> 
> Any thoughts on how to proceed?
> 
> * @corwintines could we create standalone content issues to cover the given topics? Not sure if we have any research we could include or page outlines that we could open to the community to contribute to? Maybe @emmanuel-awosika might be interested?
> * @minimalsm otherwise maybe we loop this into content strategy work ([Epic: content strategy ♟ #7240](https://github.com/ethereum/ethereum-org-website/issues/7240)) somehow?

Yeah, I briefly discussed working on this w/ @corwintines. We were supposed to have a more detailed discussion about it at Devcon. 

I've got a lot going at the moment with treatment and all, but this is something I could help with once things are settled. At least, I hope to be able to work on some of the pages before Q4 runs out.

**Comment by corwintines** [comment]
Going to close this out. Will reopen this with an outline in the future
