### ISSUE TITLE
Epic: learning quizzes 💯

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#7461]
This epic is part of our Q3 roadmap #7166 & Q4 2022 roadmap: #8399

## Description

A lot of important about Ethereum is complex and can be difficult to grasp. A great way to ensure important content is understood is by immediately testing knowledge after it is presented. The learning quizzes epic will introduce optional quizzes to [ethereum.org](http://ethereum.org/)
 content. The aim of the quizzes is to ensure that readers grasp the essential concepts to allow them to be meaningful participants in the Ethereum ecosystem.

## Deliverables

[As part of our Q3 roadmap](https://github.com/ethereum/ethereum-org-website/issues/7166), we'd like to achieve the following: 

- [x] https://github.com/ethereum/ethereum-org-website/issues/7552
- [x] https://github.com/ethereum/ethereum-org-website/issues/7553
- [x] https://github.com/ethereum/ethereum-org-website/issues/7554
- [x] https://github.com/ethereum/ethereum-org-website/issues/7555
- [x] https://github.com/ethereum/ethereum-org-website/issues/7556
- [x] https://github.com/ethereum/ethereum-org-website/issues/7557
- [x] https://github.com/ethereum/ethereum-org-website/issues/7558
- [ ] https://github.com/ethereum/ethereum-org-website/issues/7559

- To be completed

**Comment by qbzzt** [comment]
Do you already have software you're going to use? If so, which one? I've written plenty of quizzes in my life, so I can contribute here.

**Comment by konopkja** [comment]
We are building our custom solutions: preliminary design can be seen on this prototype (bottom of the page) https://www.figma.com/proto/1HxSnapMdpgFFhIHjDUytP/Learning-quizzes?page-id=266%3A189&node-id=266%3A791&viewport=-2281%2C-1848%2C0.47&scaling=min-zoom&starting-point-node-id=266%3A791

**Comment by qbzzt** [comment]
Cool, what format would you accept as input? I'd like to get started
writing quizzes.

**Comment by konopkja** [comment]
> Cool, what format would you accept as input? I'd like to get started writing quizzes.

 Created sub-tasks for individual pages we identified for the v1.  If there are any other pages you would love to write quiz content for let me know.

**Comment by hursittarcan** [comment]
Maybe it's also idea to award people that completed a specific quiz with a POAP?

**Comment by qbzzt** [comment]
I write the questions so they'll be very simple, and sometimes include hints to the answer. That is on purpose, because the point isn't to evaluate people's knowledge as much as get them to remember the concepts and know how to apply them.

**Comment by konopkja** [comment]
> 

We are considering that in the future, not this MVP release but if it gets traction then maybe in the future that is the direction we want to go.

**Comment by qbzzt** [comment]
> It looks good, thanks for the input! We will probably show around 5 - 7 questions, but the pool of questions can be even larger and we will be randomly selecting questions that appear in the widget at any given time. Maybe one piece of feedback is I would advise to keep the jargon to the minimum (nodes, gas, gwei...) the reason is a lot of our visitors are complete newcomers asking simple questions like "what is ethereum" or "why is transaction fee so high" so ideally the language could be more tailored towards such kind of audience. Otherwise its great and i like the questions! thank you :)

Thank you. I have at least three questions for each topic now. I'll see if I can come up with any more, but no promises.

The reason I use some jargon in questions is that being able to understand the jargon is one of the things we are testing (it's a skill that is developed at the same time as learning the details to which the jargon refer). I will see if I can reduce it.

**Comment by minimalsm** [comment]
Closed with #8094
