### ISSUE TITLE
Epic: Post-merge gaps

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#8285]
This epic is part of our Q4 2022 roadmap: #8399

### Description

This issue is for tracking the ethereum.org post-merge cleanup. Follows on from #7075

Tasks will be ticked off when their PRs are merged.

**New pages**
- [x] Node architecture #8449 
- [x] Block proposals #8446
- [x] PoS attack and defense   #8286
- [x] PoS FAQs #8557
- [x] PoS vs. PoW #8642
- [x] update governance page - kicked to Q1 23

**Updates to existing pages**
- [x] Update all the FAQs to have accurate information post-merge
- [x] Remove out-dated media/external resources for a post-merge environment
- [x] Ensure banners and other merge-specific components are removed #8595

**Comment by samajammin** [comment]
@jmcook1186 I think we should add the Ethereum governance page to this list of pages to update:
https://ethereum.org/en/governance/
