### ISSUE TITLE
Epic: Energy consumption page

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#8292]
This epic is part of our Q4 2022 roadmap: #8399

### Description

Overall aim is to deepen the research underlying the energy consumption page. Specific objectives:

- [x] literature search for additional references/numbers: contributor PR #8293 and my PR #8376
- [x] update text to ensure nuances and caveats are clear  #8376
- [x] look for more "primary" sources for quoted numbers  #8376
- [x] update graphics if necessary  #8376
- [x] ~~scope out incorporating "live" estimates on the page: dropped from scope—we agreed this was not worthwhile.~~
- [x] check page for post-merge consistency  #8376

**Comment by minimalsm** [comment]
Closed by #8376 🎉 thanks @jmcook1186
