### ISSUE TITLE
Epic: Change i18n Gatsby plugin/library

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8345]
This epic is part of our Q4 2022 roadmap: #8399

### Description

Not long ago, we detected that our final JS bundles (served to the clients) had a very big size which creates a slow load performance for our users impacting directly the UX and the accessibility of the site.

Since then we have run [some investigations](https://www.notion.so/efdn/Gatsby-i18n-issue-9ef381505b2448048c0ac1be90759f5d) and we have identified that the main problem is in [our i18n plugin](https://github.com/gatsbyjs/themes/issues/93). For that reason, we need to change it to one that scales well with larger sites like ours.

We need a solution that solves the 2 main issues we have been facing recently:
- Memory consumption on build stage
- Generation of big bundles

### TODO

- [x] Decide what i18n plugin/solution we want to use
 - └── We are going to use https://github.com/microapps/gatsby-plugin-react-i18next which will also change our underlying i18n lib to https://react.i18next.com/
- [x] Install the potential plugin/solution and see if it covers the 2 main issues we had #8344
- [x] Create a PR to change the i18n plugin #8406
- [x] Remove HTML from translation files #8592
- [x] ~~#8721~~

**Comment by corwintines** [comment]
@pettinarip I think this can be close dnow

**Comment by pettinarip** [comment]
Yeah! Done!
