### ISSUE TITLE
Epic: Tutorials revamp (dev & non-dev)

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#8491]
This epic is part of our Q4 2022 roadmap: https://github.com/ethereum/ethereum-org-website/issues/8399

Since launching in 2021, our developer tutorials have been a huge success. Our tutorials are purely driven by community contributions and 5% of all traffic to the website 🎉 There are now some growing pains:

- [x] too many tags in the UI
- [x] duplicate tags
- [x] outdated tutorials

**Furthermore:** 
A significant insight gathered from our user insights epic (https://github.com/ethereum/ethereum-org-website/issues/7226) is that many non-developers seek step-by-step guides on becoming successful users of Ethereum (how to get an ethereum account, how to send tokens...). We see the potential to broaden tutorials outside of mere developer tutorials to create non-technical guides.

- [x] identify key topics for non-technical guides
- [x] write the content

Have thoughts on how to improve this? We’d love to chat. [Please hop in our Discord](https://discord.gg/wKyW7cJ3PA) 😀  or comment on this issue.

**Comment by konopkja** [comment]
We have published the guides https://ethereum.org/en/guides/ which marks the final milestone for this epic. There are continuous discussions with the community on how to better structure tutorial tags. That work will done outside of this epic.
