### ISSUE TITLE
Implement UI library - 2nd migration wave

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8632]
*This is part of our [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.*

This is our 2nd list of components to migrate all of our UI components to Chakra.

### **How to contribute**

If you’d like to help with this migration, please follow these steps:

1. Leave a comment here asking which file you would want to work on.
2. We assign you to the file (by adding your handle next to the file name in the list).
    - Read and follow our [UI migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md) for some tips & guidance.
    - **If you were assigned to multiple files** then create a separate PR for each component. It will make the testing process much simpler and more organized.
3. Once you finish it (PR merged), we’ll mark it as done.
4. Repeat!

---

💡 Some of these components have some special requirements or considerations to take into account in the migration. Visit the issue attached to them to see the details.

- [x]  BannerGrid/
    - [x]  index.tsx @soheil555 #8800
- [x]  Banners/
    - [x]  PostMergeBanner.tsx @ImMiguelP #8845
- [x]  FindWallet/
    - [x]  WalletPersonasSidebar.tsx @soheil555 #8929
    - [x]  WalletFilterSidebar.tsx @TylerAPfledderer #9028
    - [x] #9982
- [x] Layer2/
    - [x] Layer2Onboard.tsx @TylerAPfledderer #10196
- [x]  Search/
    - [x] #8635 @amit-ksh 
- [x]  Staking/
    - [x]  StakingComparison.tsx @soheil555 #9046
    - [x]  StakingGuides.tsx @ImMiguelP #8821
    - [x]  StakingHierarchy.tsx @TylerAPfledderer #8686
    - [x]  StakingHomeTableOfContents.tsx @TylerAPfledderer #8703
    - [x]  StakingHowSoloWorks.tsx @ImMiguelP #8822
    - [x]  StakingProductsCardGrid.tsx @TylerAPfledderer #8679
    - [x]  StakingStatsBox.tsx @soheil555 #9017
    - [x] StakingCommunityCallout.tsx #10463
    - [x] StakingConsiderations.tsx @TylerAPfledderer #10203
    - [x] StakingLaunchpadWidget.tsx @TylerAPfledderer #10213
- [x]  BeaconChainActions.tsx @soheil555 #8720
- [x]  BugBountyPoints.tsx @amit-ksh #8820
- [x] #9953
- [x]  Codeblock.tsx #10319
- [x]  Contributors.tsx @armgp #8695
- [x] #8633 @metadiver #8738
- [x] EthExchanges.tsx @TylerAPfledderer #10222
- [x]  EthPriceCard.tsx @amit-ksh #8948
- [x] #8636 @abheektripathy
- [x]  Layout.tsx @armgp #8811
- [x]  MergeArticleList.tsx - _good first one_ @MahendraBishnoi29 #9237
- [x]  PageHero.tsx @soheil555 #8850
- [x]  ProductCard.tsx @TylerAPfledderer #8685
- [x] #8637 @amit-ksh #8794
- [x] ~~SelectableCard.tsx @MahendraBishnoi29~~
- [x]  ShardChainsList.tsx - _good first one_ @MahendraBishnoi29 #9238
- [x]  SideNav.tsx & SideNavMobile.tsx @soheil555 #9056 #9057
- [x] #8638 @amit-ksh
- [x]  StablecoinAccordion.tsx @TylerAPfledderer #9004
- [x]  StatsBoxGrid.tsx @victorpatru #8843
- [x]  TableOfContents.tsx @TylerAPfledderer #8678
- [x] #8639 @amit-ksh #8673
- [x]  Tooltip.tsx @vdusart #8684
- [x]  TranslationBannerLegal.tsx @amit-ksh #8962
- [x] #8640 @vdusart #9058
- [x]  Trilemma.tsx @TylerAPfledderer #8890
- [x]  TutorialMetadata.tsx @vdusart #8717
- [x]  UpcomingEventsList.tsx @frankiefab100 #8731
- [x]  ~~UpgradeArticles.tsx @Master7130~~
- [x] Nav/
    - [x] index.tsx @TylerAPfledderer #9808
    - [x] Dropdown.tsx @TylerAPfledderer #9808
    - [x] Menu.tsx @TylerAPfledderer #9808
    - [x] Mobile.tsx @TylerAPfledderer #9808

## Misc
- [x] #8630

**Comment by pettinarip** [comment]
@TylerAPfledderer awesome 💪🏼 assigned! ty

**Comment by pettinarip** [comment]
Assigned @MahendraBishnoi29! ty

I wanted to let you know that you still have `DismissibleCard.tsx` assigned to you from the 1st wave. Please, let me know if you are still considering in working on it or if I can reassign it to someone else.

**Comment by Master7130** [comment]
Can I work on `UpgradeArticles.tsx`?

**Comment by pettinarip** [comment]
Assigned @Master7130, thanks!

**Comment by marcellamalune** [comment]
Hi @pettinarip I'd like to work on a couple components! No preference 🙂

**Comment by pettinarip** [comment]
👋🏼 @marcellamalune thanks. I've assigned `ButtonDropdown.tsx` & `Codeblock.tsx` to you.

**Comment by armgp** [comment]
Hey can I work on FileContributors.tsx

**Comment by TylerAPfledderer** [comment]
@pettinarip Also assign to me `StakingProductsCardGrid` for the same reason as I stated above! 😅

**Comment by pettinarip** [comment]
@armgp done! & thanks

**Comment by pettinarip** [comment]
> @pettinarip Also assign to me `StakingProductsCardGrid` for the same reason as I stated above! (I promise I won't ask for any more unless absolutely necessary sweat_smile )

No worries :) thank you for being aware of those potential conflicts/dependencies.

**Comment by MahendraBishnoi29** [comment]
> Assigned @MahendraBishnoi29! ty
> 
> I wanted to let you know that you still have `DismissibleCard.tsx` assigned to you from the 1st wave. Please, let me know if you are still considering in working on it or if I can reassign it to someone else.

nope I'm working on it 💪🏻 also i think these are easy ones so i will complete them all so please assign me all these 😁🚀

**Comment by pettinarip** [comment]
@MahendraBishnoi29 great, good to hear 🙌🏼

**Comment by frankiefab100** [comment]
@pettinarip can I work on `UpcomingEventsList.tsx`

**Comment by MahendraBishnoi29** [comment]
> @MahendraBishnoi29 great! good to hear 🙌🏼 

assigned me? 😀

**Comment by Pranav-yadav** [comment]
Hey @pettinarip !
I would like to help w/
>  TranslationBannerLegal.tsx

**Comment by soheil555** [comment]
Hi @pettinarip I'd like to work on `BeaconChainActions.tsx`, `BugBountyPoints.tsx,` and `PageHero.tsx` components.

**Comment by adi29raj** [comment]
Hi @pettinarip I'd like to work on a couple components! Search will be preferred.

**Comment by pettinarip** [comment]
@adi29raj assigned

**Comment by soheil555** [comment]
Hey @pettinarip 

I've completed the migration of `BeaconChainActions.tsx`.
I would like to work on another component.

**Comment by ImMiguelP** [comment]
Hey @pettinarip can I get  `PostMergeBanner.tsx` , StakingGuides.tsx ,  StakingHowSoloWorks.tsx ,assigned to me please.

**Comment by pettinarip** [comment]
Assigned `BannerGrid/index.tsx` @soheil555 & the requested ones to you @ImMiguelP. Ty!

**Comment by amit-ksh** [comment]
Hi @pettinarip I'd like to work on a couple of components!

**Comment by soheil555** [comment]
Hey @pettinarip If possible, I would like to work on a couple more components. No preference.

**Comment by victorpatru** [comment]
Hey @pettinarip. Contributor to the first wave of migration here 👋 . Would love to tackle some components that are part of this second wave of migrations. Thanks!

**Comment by pettinarip** [comment]
@amit-ksh @soheil555 @victorpatru
Awesome guys! thanks for the help 💪🏼 I've assigned one component to each one of you.

**Comment by soheil555** [comment]
Hey @pettinarip , I'd like to work on a couple more components. No preference.

**Comment by TylerAPfledderer** [comment]
@pettinarip I'll take on `Trilemma`! 💪🏼

**Comment by pettinarip** [comment]
Assigned! @TylerAPfledderer 🙏🏼

**Comment by amit-ksh** [comment]
Hey @pettinarip! I'd like to work on a couple of components.

**Comment by TylerAPfledderer** [comment]
Hey @pettinarip it would be best for me to take `StablecoinAccordion` as I missed that it is related to PR #8601, and is also related to a bug (#8923) which I am also creating a PR for.

**Comment by pettinarip** [comment]
Awesome @amit-ksh I've assigned `EthPriceCard.tsx` and `TranslationBannerLegal.tsx` to you. Thanks so much for the help 🙏🏼

**Comment by pettinarip** [comment]
> Hey @pettinarip it would be best for me to take `StablecoinAccordion` as I missed that it is related to PR #8601, and is related to a bug (#8923) which I am also creating a PR for.

Got it! That is a good point, I've assigned it to you. And thanks for those PRs 💪🏼

🎅🏼

**Comment by albertg361** [comment]
Ok i will get it done

**Comment by soheil555** [comment]
Hey @pettinarip I'd like to work on a component. No preference.

**Comment by pettinarip** [comment]
@soheil555 assigning `StakingStatsBox` to you, thanks!

**Comment by TylerAPfledderer** [comment]
@pettinarip I can take the `WalletFilterSidebar` 💪🏼

**Comment by soheil555** [comment]
@pettinarip Can I work on `StakingComparison.tsx`

**Comment by pettinarip** [comment]
@TylerAPfledderer @soheil555 assigned! thanks & happy new year btw! 🥂

**Comment by soheil555** [comment]
@pettinarip Can I work on `SideNav.tsx` & `SideNavMobile.tsx`?

**Comment by pettinarip** [comment]
@soheil555 assigned!

**Comment by benlazzero** [comment]
@pettinarip Hey! can I get #8640? (TranslationLeaderboard)

**Comment by pettinarip** [comment]
Hey @benlazzero thanks for your interest in helping in this migration.

Unfortunately, that issue is already assigned to a contributor but if you don't mind there are a few other files from the first wave that still need to be migrated. I could assign one of them to you if you are interested. Those are:
- AdoptionChart.tsx
- AssetDownload.tsx
- BoxGrid.tsx

LMK which one do you prefer and I assign it to you :)

**Comment by benlazzero** [comment]
@pettinarip Oh my bad. I will do AssetDownload.tsx then, Thanks!

**Comment by pettinarip** [comment]
Awesome! I've assigned it to you @benlazzero ty

**Comment by soheil555** [comment]
Hey @pettinarip Can I work on  `AdoptionChart.tsx`?

**Comment by pettinarip** [comment]
> Hey @pettinarip Can I work on `AdoptionChart.tsx`?

For sure. Assigned! thanks

**Comment by soheil555** [comment]
@pettinarip  Can I work on `BoxGrid.tsx`?

**Comment by pettinarip** [comment]
> @pettinarip Can I work on `BoxGrid.tsx`?

Sure! assigned 🙏🏼

**Comment by pettinarip** [comment]
Hey @marcellamalune @MahendraBishnoi29 @Master7130 👋🏼 

I wanted to double-check if you are still interested in working on the assigned components in this issue and in #6374. Otherwise, I could reassign them to other contributors.

Thanks!

**Comment by MahendraBishnoi29** [comment]
@pettinarip yes, I had a query regarding the component that I asked you about on discord please check it.

**Comment by marcellamalune** [comment]
> Hey @marcellamalune @MahendraBishnoi29 @Master7130 👋🏼
> 
> I wanted to double-check if you are still interested in working on the assigned components in this issue and in #6374. Otherwise, I could reassign them to other contributors.
> 
> Thanks!

Hey @pettinarip yes I'm working on them! I'll submit PRs in the next days 😄 
Thank you for the update

**Comment by pettinarip** [comment]
@MahendraBishnoi29 @marcellamalune nice! yea, no major rush.

**Comment by Master7130** [comment]
@pettinarip Sorry for the delay. I'll have my PR ready in a couple days.

**Comment by pettinarip** [comment]
Awesome @Master7130 thanks!

**Comment by rishisundar** [comment]
Hey, can I work on something? Don't have any preference. Would love to contribute!

**Comment by shariqanwar20** [comment]
Hey @pettinarip is there anything I can contribute to. Would love to help

**Comment by pettinarip** [comment]
@rishisundar @shariqanwar20 we've just created a new GH issue to start migrating the pages and templates. Check it out! #9353

**Comment by Seek4samurai** [comment]
Hi @pettinarip can I work on `UpgradeArticles.tsx`? Let me know.

**Comment by pettinarip** [comment]
Hey @Seek4samurai thanks for reaching out. That file is assigned to @Master7130. @Master7130 are you still interested in doing that migration? or can we assign it to @Seek4samurai ?

**Comment by Seek4samurai** [comment]
> Hey @Seek4samurai thanks for reaching out. That file is assigned to @Master7130. @Master7130 are you still interested in doing that migration? or can we assign it to @Seek4samurai ?

Um sadly I've started working over it. Though let me know about it. Thanks.

**Comment by TylerAPfledderer** [comment]
@pettinarip Could you go ahead and tag me for the `WalletTable` component? It looks like this one needs a major overhaul (`table` elements as rows inside a `table` element 😬 )

**Comment by pettinarip** [comment]
Oh yea, that's a pretty big file.

> table elements as rows inside a table element

Oh...didn't know about that! 😬 

Thank you sir!

**Comment by TylerAPfledderer** [comment]
@pettinarip commenting per our recent discussion to gain assignment for those listed under "Currently Blocked" to help get them over the finish line.

`WalletTable` already has an open PR to be marked (The reference directly above this comment ☝🏼 )

**Comment by SouravInsights** [comment]
Hey, @pettinarip 👋 Is there still any components & pages that needs to be contributed? I can help out..

**Comment by pettinarip** [comment]
🏄🏼‍♂️ wave 2 done!

**Comment by Seek4samurai** [comment]
Hi @pettinarip, glad this is done! What's next for the Roadmap?

**Comment by pettinarip** [comment]
Hi @Seek4samurai! thanks for all the work you put into this effort 🙌🏼 

In terms of this epic, not much. I'll run some cleanup tasks to double-check that we are not using any `styled` and/or deprecated components.

In terms of UI, the idea is to keep working on DS implementation #9548 and implement necessary refactors as we create and implement new components/abstractions.

Finally, we are in the early stage of migrating our infra to NextJS. More info about this soon when we share our Q3 roadmap.
