### ISSUE TITLE
Update "Deploy and review process"

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#9059]
### Is your feature request related to a problem? Please describe.

We added a new doc outlining our review process:
https://github.com/ethereum/ethereum-org-website/blob/dev/docs/deploy-and-review-process.md#deploy-and-review-process

I think this is a great start! Some feedback on how we might improve it...

### Describe the solution you'd like

Some ideas & open questions:
- I think there should be distinction between the review process for issues vs PRs (with PRs generally taking priority)
- Should we have an initial "groom" of new issues/PRs?
  - e.g. within 2 days, any issue is reviewed & triaged, meaning:
    - we reply to the issue, linking to this doc, to set expectations
    - we label it & prioritize it accordingly
    - we assign it to someone if relevant (e.g. if the person who opened the issue volunteered to work on it)
    - we label it by the categories outlined in the doc (should each section have a label, e.g. "translations", "bug", "content")?
  - To me, this acts as a good 1st step to ensure we read every issue quickly in order to prioritize it if needed (vs. potentially trying to address the issue with a PR on the initial review). In this way, there'd essentially be 2 sweeps of any issue/PR:
    - 1) initial triage
    - 2) reviewing/merging the PR or solving the issue by opening a new PR
  - I like that we outline "We aim to have every new PR merged or closed within 30 days of opening" - I think it'd be nice to have a similar goal for issues
- "Bug fixes" should be high priority
  - I think we should break out bug fixes from features to give them higher priority (e.g. within 5 days). Currently they're grouped together into one "Feature and bug fixes" category
- With "bug fixes" broken into an independent category, I'd lump "Content and features" together
- I'd suggest updating each category to "within X days" vs. providing a range ("1-X days")
- Do we cover all listing policy categories with this current guide?

### Describe alternatives you've considered

Keep process as is :)

### Additional context

Original PR #8476

### TODO
- [x] Update current PR review process
- [x] Create issue review process
- [x] Create documentation on "How we work in GitHub"

**Comment by samajammin** [comment]
Some more details on what adding a triage step to this process might look like...

1. Whenever a new issue/PR is opened, we have a bot label it with a `needs-triage` label
2. 1st priority for core reviewer is to triage, so:
    - filter PRs by that label & triage them (as outlined above)
    - filter issues by that label & triage them (as outlined above)
3. 2nd priority for core reviewer (once no issues or PRS have a `needs-triage` label) is to tackle open PRs/issues based on their priority, e.g.:
    - review & merge all bug fix PRs
    - review & fix all bug issues
    - review & merge all translation PRs
    - review & merge all content PRs
    - review & open PRs for all content issues

**Comment by corwintines** [comment]
I agree that there should be a separate process for PR's and issues. Will be working to get a draft out for the issue review process this week.

But, to comment on some of the specifics here:

> Should we have an initial "groom" of new issues/PRs?
e.g. within 2 days, any issue is reviewed & triaged, meaning:
we reply to the issue, linking to this doc, to set expectations
we label it & prioritize it accordingly
we assign it to someone if relevant (e.g. if the person who opened the issue volunteered to work on it)
we label it by the categories outlined in the doc (should each section have a label, e.g. "translations", "bug", "content")?
To me, this acts as a good 1st step to ensure we read every issue quickly in order to prioritize it if needed (vs. potentially trying to address the issue with a PR on the initial review). In this way, there'd essentially be 2 sweeps of any issue/PR:
initial triage
reviewing/merging the PR or solving the issue by opening a new PR
I like that we outline "We aim to have every new PR merged or closed within 30 days of opening" - I think it'd be nice to have a similar goal for issues

Agree with all of this, and will incorporate in the issue process doc

> "Bug fixes" should be high priority
I think we should break out bug fixes from features to give them higher priority (e.g. within 5 days). Currently they're grouped together into one "Feature and bug fixes" category
With "bug fixes" broken into an independent category, I'd lump "Content and features" together

I will draft something for this change to discuss, but does make sense to me.

> I'd suggest updating each category to "within X days" vs. providing a range ("1-X days")

Agree, would clean this up.

> Do we cover all listing policy categories with this current guide?

At the moment I think we cover all scenarios we get at the moment, but I imagine there will be more to add in the future. Will keep an eye out for those.


> Some more details on what adding a triage step to this process might look like...
Whenever a new issue/PR is opened, we have a bot label it with a needs-triage label
1st priority for core reviewer is to triage, so:
filter PRs by that label & triage them (as outlined above)
filter issues by that label & triage them (as outlined above)
2nd priority for core reviewer (once no issues or PRS have a needs-triage label) is to tackle open PRs/issues based on their priority, e.g.:
review & merge all bug fix PRs
review & fix all bug issues
review & merge all translation PRs
review & merge all content PRs
review & open PRs for all content issues

This seems like a solid process to follow. After making the issue process, I will draft a meta process to cover how we work and use these. Seems this can be broken out a bit.

Will come up with action steps in GH grooming and post here. 

Assigning this to myself.

**Comment by wackerow** [comment]
Should we close this now that #9521 and #9538 are merged?

**Comment by corwintines** [comment]
Yes I think so. Going to close this out.
