### ISSUE TITLE
Epic: Staking Push Withdrawals

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#9101]
- Part of #9090 

## Intro

After over two years since the launch of the Beacon Chain, the ability for stakers to unlock their funds and rewards is soon approaching. EIP-4895, slated to be included in the upcoming Shanghai upgrade, enables **push withdrawals** from the Beacon Chain.

Currently the [ethereum.org](http://ethereum.org) website has very limited information related to staking withdrawals other than simply noting they are not available yet, and are proposed for inclusion in the next upgrade. 

This change brings new questions for all users of Ethereum that we will work to address.

## User personas to consider

- Not-yet-staker (holder of ETH or not)
- Liquid staking derivative holders
- Home stakers
    - Looking to continue staking, but claim rewards
    - Looking to exit, and claim all
    - Slashed, wondering how to reclaim remaining
- Ethereum developers/techies looking to know more details

## Scope of this epic

- **Goal**: Provide ethereum.org focused content related to education, steps needed to be taken surrounding staking withdrawals, and ELI-5 explanation of how things will work moving forward
- **Location of page**: Currently see this as a one-pager that lives at: `/staking/withdrawals`
- **Target audience**: Broadly anyone interested in staking, thus keeping this as a relatively low technical level. See _out of scope_ section.

### Out of scope

There is a parallel epic related to updating the Staking Launchpad with more information regarding withdrawals. Technical details related to exactly how stakers can get prepared for push withdrawals, including generation of withdrawal keys, broadcasting of withdrawal credentials, and how to exit fully, will be out of scope for ethereum.org, but are planned for inclusion on the Staking Launchpad.

## To do

- [ ] Finalize design considerations for how to present new information most effectively
- [ ] Write copy for new `/staking/withdrawals/` page
- [ ] Write copy for new section on each of the individual staking pages
- [ ] Consider technical copy additions to the dev docs
- [ ] Clean up references to Shanghai with available information prior to the upgrade
- [ ] Post-Shanghai clean-up to fix up any remaining references, or any needed tense-changes once changes are live
- [ ] Content review from community and core devs for accuracy and completeness

**Comment by corwintines** [comment]
@wackerow I checked off a couple of these todos. Is the plan here to keep this epic for cleanup around Shanghai then based on these todos?

**Comment by wackerow** [comment]
@corwintines Yes, that was the plan here
