### ISSUE TITLE
Epic: Ethereum.org maintenance

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#9212]
Part of https://github.com/ethereum/ethereum-org-website/issues/9090

## Intro
Get through the backlog of PR’s and issues to get us to maintenance mode. Maintenance mode will be when we can deliver on the processes we are outlining for PR’s and issues. Throughout this quarter we will also look for improvements that can be made to the process to bring to Q2.

## Scope of this epic
- Get to maintenance mode for pull requests in the repository, which is defined by delivering on this [process](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/deploy-and-review-process.md)
- Define maintenance mode for issues, and publish this process
- Get to maintenance mode for issues in the repository, which will be defined above
- Research opportunities to improve the contributor and maintenance process

## To do
- [ ] Catch up on pull requests
- [x] Create an issue review policy
- [ ] Catch up on issue reviews based on the new policy
- [x] Look for new ways to improve the maintenance process to make maintenance mode easier to achieve

**Comment by raynemang** [comment]
How can one apply to be a reviewer of pull requests?

I would be very interested in helping get through the backlog of pull requests relating to information, written prose, documents etc.

**Comment by corwintines** [comment]
Hey @raynemang, sorry for late response. 

You can always contribute to reviews on PRs :) The core team does a final review and merge, but if you want to hop in and make suggestions if you notice anything that is always welcome!
