### ISSUE TITLE
2023 Q1: Protocol Roadmap Content epic tracker

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/ethereum-org-website#9242]
This issue is for tracking progress on the 2023 Q1 roadmap epic "Protocol Roadmap Content".

Design ideation is also happening in [figma](https://www.figma.com/file/zI3N68ZVT4L65OoE97N9H8/Roadmap-page?node-id=1%3A13&t=5WxCQWfWUncJtE9q-0)

TODO:

- [x] discuss initial proposal for new content with e.org team
- [x] onboard to figma and sketch out page designs
- [x] agree final structure and content plan with team

**Existing pages to update:**

- [x]  `/upgrades`
- [x] `/upgrades/sharding` (either remove page or complete rewrite to include 4844 and danksharding)
- [x] `history` (to include new subpages on merge and beacon chain)
- [x] audit for links to merge, beacon chain and sharding pages and update to point to new location

Note - reverted page moves - not included in the v1/MVP release because of downstream impacts on translations etc. Will revisit for v2.

**New pages to add:**

to `/upgrades`:

- [x] subpage 1: security
- [x] subpage 2: scaling
- [x] subpage 3: barriers to entry
- [x] subpage 4: future proofing

topic subpages:
- [x] Danksharding
- [x] single slot finality
- [x] PBS
- [x] statelessness
- [x] DVT (not included in v1/MVP launch)
- [x] withdrawals (Paul did this in separate epic)
- [x] DAS (likely update existing page instead of starting new one)
- [x] account abstraction
- [x] light clients (not included in v1/MVP launch)
- [x] portal network (decided it's enough to mention in statelessness page)
- [x] verkle trees

**pages to move:**

Note - reverted this - not included in the v1/MVP release because of downstream impacts on translations etc. Will revisit for v2.

- [x] `/upgrades/merge` to `history/merge`
- [x] `/upgrades/beacon-chain` to `history/beacon-chain`

NB - page moves reinstated after launch. Now completed.

**Dev tasks**
for v1/MVP launch:

- [x] build pages and generate preview deploy for review
- [x]  Migrate upgrades/vision -> roadmap/vision (update redirects and links as well for this)  
- [x] Summary points back in headers  
- [x]  Buttons in read more sections  
- [x]  Translations for breadcrumbs    
- [x]  Event tracking on FAQ  
- [x]  Style cards  
- [x]  How is the roadmap defined section implemented with image  

**Outstanding design/dev tasks**
These are the final pieces to add before closing out this epic
- [x] add AI illustrations
- [x] finalize design for page navigation

stretch goal:
- implement the page nav design

**Comment by samajammin** [comment]
@jmcook1186 could you please link to the Figma files you mentioned you've been working on to draft this?

**Comment by jmcook1186** [comment]
closing as completed
