### ISSUE TITLE
Implement UI library - Migrate pages & templates

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#9353]
*This is part of our [Implement UI library](https://github.com/ethereum/ethereum-org-website/issues/6374) epic.*

Our final step on the UI migration! time to migrate the pages & templates.

### **How to contribute**

If you’d like to help with this migration, please follow these steps:

1. Leave a comment here asking which file you would want to work on.
2. We assign you to the file (by adding your handle next to the file name in the list).
    - Read and follow our [UI migration guide](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/chakra-migration-guide.md) for some tips & guidance.
    - **If you were assigned to multiple files** then create a separate PR for each component. It will make the testing process much simpler and more organized.
3. Once you finish it (PR merged), we’ll mark it as done.
4. Repeat!

- [x] `src/pages/`
  - [x] wallets/find-wallet.tsx @soheil555 #9390
  - [x] contributing/translation-program/acknowledgements.tsx @amit-ksh #9397
  - [x] contributing/translation-program/contributors.tsx @amit-ksh #9369
  - [x] community.tsx @soheil555 #9410
  - [x] staking/index.tsx @mlCode111 #9398
  - [x] staking/deposit-contract.tsx @mlCode111 #9549
  - [x] stablecoins.tsx @alex1092 #9635
  - [x] learn/index.tsx @soheil555 #9422
  - [x] assets.tsx @MrJithil #9406
  - [x] bug-bounty.tsx @Seek4samurai #9475
  - [x] languages.tsx @MahendraBishnoi29 #10014
  - [x] index.tsx @TylerAPfledderer #9364
  - [x] 404.tsx #10318
  - [x] get-eth.tsx @vdusart #9627
  - [x] run-a-node.tsx #10534
  - [x] upgrades/get-involved/index.tsx @amit-ksh #9572
  - [x] upgrades/vision.tsx @amit-ksh #9524
  - [x] upgrades/index.tsx @amit-ksh #9473
  - [x] developers/local-environment.tsx @soheil555 #9583
  - [x] developers/index.tsx @Seek4samurai #9933
  - [x] developers/tutorials.tsx @vdusart #10104
  - [x] developers/learning-tools.tsx @Seek4samurai #10348
  - [x] layer-2.tsx @TylerAPfledderer #9404
  - [x] studio.tsx @rishisundar #9518

- [x] `src/pages-conditional/`
  - [x] wallets.tsx @ameeetgaikwad #9500
  - [x] eth.tsx #10470
  - [x] what-is-ethereum.tsx #10468
  - [x] dapps.tsx @amit-ksh #10089

- [x] `src/templates/`
  - [x] docs.tsx @amit-ksh #10375
  - [x] tutorial.tsx @rishisundar #10173
  - [x] upgrade.tsx @amit-ksh #9670
  - [x] roadmap.tsx #10549
  - [x] staking.tsx @soheil555 #10019
  - [x] use-cases.tsx @TylerAPfledderer #9634
  - [x] static.tsx @soheil555 #9631

**Comment by soheil555** [comment]
Hey, @pettinarip I'd like to work on `wallets/find-wallet.tsx`?

**Comment by vdusart** [comment]
Hey @pettinarip ready for some files 😁🚀

**Comment by amit-ksh** [comment]
Hey @pettinarip, I'd like to work on `contributing` pages

**Comment by yash251** [comment]
Hello team, I would love to start with 404.tsx

**Comment by rishisundar** [comment]
Hey @pettinarip, I would like to work on `src/templates/tutorial.tsx` and `src/pages/studio.tsx`.

**Comment by shariqanwar20** [comment]
Hey @pettinarip would love to work on some page. No preference

**Comment by ameeetgaikwad** [comment]
Hey, @pettinarip give me 1-2 pages, for now. Give them according to your preference.

**Comment by SNikhill** [comment]
Greetings @pettinarip 

I shall like to take just a single file this time.
Preferably: `src/templates/docs.tsx`

**Comment by MahendraBishnoi29** [comment]
@pettinarip assign `languages.tsx` and `404.tsx` to me I've already started working on these

**Comment by pettinarip** [comment]
Woooohoooo! lfg 🎉 

@soheil555 @amit-ksh @yash251 @rishisundar @ameeetgaikwad @SNikhill @MahendraBishnoi29 @TylerAPfledderer @vdusart @shariqanwar20 @MrJithil 

Assigned! 🙏🏼

**Comment by TylerAPfledderer** [comment]
@pettinarip so you know that I like to code split the logic of a component sometimes into it's own `useHook`. Would you like that with the pages, or leave them in the same file?

**Comment by mlCode111** [comment]
Hello there! @pettinarip I'll start with staking/index.tsx. You can assign this to me.

**Comment by mlCode111** [comment]
@TylerAPfledderer I'm talking about the /staking page, not the home page. Thanks for the reference.

**Comment by pettinarip** [comment]
Assigned @mlCode111 ty!

**Comment by soheil555** [comment]
Hey @pettinarip Can I work on `community.tsx`?

**Comment by amit-ksh** [comment]
Hey @pettinarip, I'd like to work on `upgrades` pages.

**Comment by Seek4samurai** [comment]
Hi @pettinarip ! Would like to work on the Bug Bounty Page.

**Comment by mlCode111** [comment]
Hi @pettinarip , I'll move on to page `staking/deposit-contract.tsx`. Thanks!

**Comment by pettinarip** [comment]
@soheil555 @amit-ksh @Seek4samurai @mlCode111 assigned! thanks 🙏🏼

**Comment by soheil555** [comment]
Hey @pettinarip , Can I work on `learn/index.tsx`?

**Comment by amit-ksh** [comment]
Hey @pettinarip! Can you please assign me `upgrades/vision.tsx` page?

**Comment by ameeetgaikwad** [comment]
@pettinarip opened a pr #9497.

**Comment by ameeetgaikwad** [comment]
@pettinarip can you assign me dapps.tsx  as well?

**Comment by ameeetgaikwad** [comment]
@pettinarip can you assign me dapps.tsx from pages-conditional

**Comment by Seek4samurai** [comment]
Hey @pettinarip, if no one is assigned to `developers/index.tsx` I can work over that!

**Comment by amit-ksh** [comment]
@pettinarip can you please assign me `upgrades/get-involved/index.tsx` page?

**Comment by pettinarip** [comment]
@ameeetgaikwad @Seek4samurai @amit-ksh assigned! thanks guys!

**Comment by pettinarip** [comment]
`stablecoins.tsx` is yours now @alex1092, ty

**Comment by soheil555** [comment]
Hey @pettinarip, Can I work on `developers/local-environment.tsx`?

**Comment by amit-ksh** [comment]
Hey @pettinarip, can you assign me `upgrade.tsx` from **src/templates.**

**Comment by soheil555** [comment]
Hey @pettinarip, can I work on `static.tsx`?

**Comment by TylerAPfledderer** [comment]
@pettinarip I'll grab the `use-cases` page

**Comment by pettinarip** [comment]
Niiiicee! @amit-ksh @soheil555 @TylerAPfledderer assigned folks 💪🏼 thanks guys

**Comment by amit-ksh** [comment]
Hey @pettinarip, can I work on `job. tsx` template

**Comment by pettinarip** [comment]
Assigned @amit-ksh 💪🏼 ty

**Comment by pettinarip** [comment]
@MahendraBishnoi29 @yash251 @shariqanwar20 @vdusart @SNikhill @rishisundar

Hey! pinging you guys to double-check if you are still interested in working on the assigned files. If you are not, please let us know so that we can reassign them 🙏🏼 🙏🏼 

Thanks!

**Comment by vdusart** [comment]
Yes @pettinarip sorry for the delay. I'll do it soon 😉

**Comment by shariqanwar20** [comment]
Hey Sorry for the delay, some part of it is left. Will open a PR soon

**Comment by MahendraBishnoi29** [comment]
will submit it today 🚀

**Comment by rishisundar** [comment]
Hey @pettinarip Sorry about the delay. Will raise a PR soon

**Comment by sahildotdev** [comment]
Hey, @pettinarip 👋 Happy to contribute.. Can you please assign me anything?

**Comment by amit-ksh** [comment]
Hey @pettinarip, is there anything left I can work on?

**Comment by pettinarip** [comment]
@amit-ksh thanks for asking :) Yes, I've re-assigned the docs template to you.

At this point, I'd say that `run-a-node.tsx` is also available if you want to work on that as well.

**Comment by Seek4samurai** [comment]
Hi @pettinarip I've submitted the PR for developers/learning-tools.tsx page.
Can you assign me the unassigned `run-a-node.tsx`, if it's still unassigned?

**Comment by pettinarip** [comment]
> Hi @pettinarip I've submitted the PR for developers/learning-tools.tsx page. Can you assign me the unassigned `run-a-node.tsx`, if it's still unassigned?

Wohoo! I saw that, will review it soon. Sure! assigning...ty

**Comment by minimalsm** [comment]
Hey @sahildotdev 

Thanks for offering to help; just confirming you've seen you're assigned to the `src/pages-conditional/eth.tsx` page? Let us know if that is okay 😀🫡

**Comment by pettinarip** [comment]
Pages & templates done! thanks everyone! 🥳
