### ISSUE TITLE
Epic: Implementation of the Design System

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#9546]
_This is an epic that makes up part of the [ethereum.org Q1 roadmap](https://github.com/ethereum/ethereum-org-website/issues/9090)_

## Description

Now that the first version of our Design System is complete and we have already migrated most of the UI components to Chakra, we can proceed with implementing the DS on [ethereum.org](https://ethereum.org/). Our DS is a set of guidelines and reusable components that will help ensure a consistent and user-friendly experience across the website.

To implement the DS, we will follow the same structure we used in its development. We’ll break down the implementation process into three stages:

- [x] #9548 - In the first stage, we will focus on integrating core components and the foundation styles.
- [ ]  #11117 - The second stage will involve adding more complex or composed components, and adapting existing ones as needed.
- [ ]  **Implement DS v3** - Finally, in the third stage, we will focus on special pages that have custom designs. For instance, the Layer 2 and Find a Wallet pages.

For more information about our DS and the migration to Chakra, check out the links below:

- Design System: https://github.com/ethereum/ethereum-org-website/issues/6284
- Migration of UI components: https://github.com/ethereum/ethereum-org-website/issues/6374

### New folder structure for new components

Since we've incorporated [Storybook and Chromatic](https://github.com/ethereum/ethereum-org-website/issues/8490) into our workflow, from now on we need to create stories for every component we create or modify based on the DS.

```sh
// at the end of the implementation, all components should have
// the following structure

components/
  NewComponent/
    index.tsx
    NewComponent.stories.tsx
```

Going forward, any changes made to the UI will require approval or denial on [Chromatic](https://www.chromatic.com/builds?appId=63b7ea99632763723c7f4d6b), which will become an additional step in our review process.

**Comment by konopkja** [comment]
@pettinarip  should we close this one now?

**Comment by wackerow** [comment]
@konopkja My take here is we should probably sync up to reevaluate our plans for the design system since much time has passed since the original initiative. 

Related open issues:
- #9545 (This one)
- #9548 
- #11117
- #10744
- #10886
- Maybe others I missed?

Given the many migrations since then, e.g., Next.js 14 (and soon™️ v15), shadcn/ui with TailwindCC v3 (soon™️ v4), and recent discussion about updating the DS again, we may want to consider calling this complete to the extent it's been implemented, and abandoning the rest while we reevaluate.

**Comment by pettinarip** [comment]
@konopkja closing this as it's mostly outdated now. The initial DS implementation is complete and already integrated across most of the codebase.

Agree with @wackerow. We should take some time to reevaluate the DS and extend it to cover more complex and reusable components, which was largely missing from this epic.
