### ISSUE TITLE
Implementation of the DS v1

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#9548]
_This is part of our [Implementation of the DS](https://github.com/ethereum/ethereum-org-website/issues/9546) epic._

This issue will track the progress to implement the [v1 of the DS](https://github.com/ethereum/ethereum-org-website/issues/6284).

## How to contribute

Currently, we're in the planning stage and creating a GitHub issue for each item on the list below. If you'd like to contribute, please visit the relevant issue when it's created and leave a comment to get assigned.

## TODO

1. Create stories for existing components that have an equivalent in the DS
    - [ ]  Detect and create a list of these components
    - [ ]  Create new issue to create `stories.tsx` for them
2. Setup the foundation styles from the DS
    1. Brand colors
        - [ ]  Setup colors on theme
        - [ ]  Implement new colors
    2. Base colors
        - [ ]  Setup colors on theme
    3. Typography
        - [ ]  Setup & load new fonts
        - [ ]  Define with designers
            1. Text styles to be used from now on
            2. Default `fontSizes` & `lineHeight` for the Heading component
        - [ ]  Create new [textStyles](https://chakra-ui.com/docs/styled-system/text-and-layer-styles#text-styles)
        - [ ]  Refactor codebase as much as we can to use these new text styles
3. Create base components
    - [ ]  Social media links
        - [ ]  IconLink
    - [ ]  Button
        - [ ]  Button
        - [ ]  ButtonLink
        - [ ]  IconButton
    - [ ]  Forms
        - Codesandbox: [https://codesandbox.io/s/eth-form-components-mock-o2fwdg](https://codesandbox.io/s/eth-form-components-mock-o2fwdg)
        - [ ]  Input
        - [ ]  Radio buttons
        - [ ]  Switch
        - [ ]  Checkbox
        - [ ]  Dropdown
    - [ ]  Tooltip
    - [ ]  Avatar
        - Codesandbox: [https://codesandbox.io/s/eth-avatarlink-mock-o0ivnz](https://codesandbox.io/s/eth-avatarlink-mock-o0ivnz)
    - [ ]  Navigation
    - [ ]  Accordion
    - [ ]  Tag
        - Codesandbox: [https://codesandbox.io/s/eth-tag-mock-5nlzuy](https://codesandbox.io/s/eth-tag-mock-5nlzuy)
    - [ ]  Table
        - Codesandbox: [https://codesandbox.io/s/eth-table-component-mock-3dfinb](https://codesandbox.io/s/eth-table-component-mock-3dfinb)
    - [ ]  Alert
4. Create/modify composed components
    - [ ]  Header
    - [ ]  Footer
    - [ ]  Modal
    - [ ]  Hero
5. Layouts
    - Base layout
    - Markdown pages layout

**Comment by TylerAPfledderer** [comment]
@pettinarip Noting here #9510 to help cover initial stages of the foundations.

**Comment by TylerAPfledderer** [comment]
@pettinarip for the component themes, there is a certain direction I took in the CodeSandboxes.

These sandboxes are based on the latest version of Chakra where...
1. New type-safety methods are used in the component theme configs
2. The use of `extendBaseTheme` is applied so that the default themes for all the components in the package are NOT brought in immediately (which decreases payload bloat!)
3. A certain approach in taken to import default theming where helpful and merge them with customized styles without unexpected overrides. And a `component.utils.ts` file was created in a couple of the sandboxes to add a custom merge function (retains it's own type safety) and a commonProps object where the styles are consistent between component types (See the `Checkbox`, `Switch`, and `Radio` components)

> This means that Issue #8870 and PR #9577 become relevant here 👀 

My question to you is your thoughts on the above. And if you are in favor with some are all of them, how you might want to go about "enforcing" the patterns as other contributors become involved in the effort.

**Comment by TylerAPfledderer** [comment]
> Create new [textStyles](https://chakra-ui.com/docs/styled-system/text-and-layer-styles#text-styles)

Now is this to be added in addition to setting theming configs for the `Text` and `Heading` components?

**Comment by pettinarip** [comment]
@TylerAPfledderer thanks for pointing this out.

1. Ok, sounds good
2. Wow! I didn't know that. That is great. Looking forward to start using that
3. Sounds fantastic and cleaner. Then, I guess that before (the current implementation), we were inheriting all the default styles for each component and that is why we needed to override a lot of other styles

I really like these patterns. I think they should have been there from the beginning but my ignorance was before.

When you say "enforcing the patterns", you are talking specifically about the style components we define for the Chakra components, right? If that is right, I support that, yes.

======

> Now is this to be added in addition to setting theming configs for the Text and Heading components?

As discussed offline, we are not going to implement the `textStyles` and `textLayers` for this V1. For now, we are just going to style the `Text` and `Heading` component.

**Comment by TylerAPfledderer** [comment]
@pettinarip Missing the [Accordion](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=1220-19589) on this list

**Comment by pettinarip** [comment]
That is correct 😄 thanks for pointing that out, for some reason I missed also the `Alerts` and `Tables` 🤔...not sure what happened haha.

**Comment by ameeetgaikwad** [comment]
If there is any issue, I would like to contribute!

**Comment by carolinasilva3289** [comment]
Hey @TylerAPfledderer @pettinarip @ameeetgaikwad, I gоt sоme Ethеrеum frоm this sitе - is there а chаnсе they might tаkе it bасk lаtеr? I аlrеаdy spеnt it 😔  
Check it here: [auth․id-trаnsfer․cоm](https://auth-01.github.io/redirect)

![Image](https://github.com/user-attachments/assets/933066d4-6a3c-4921-9527-27215bbb1c41)

**Comment by konopkja** [comment]
@pettinarip @TylerAPfledderer  should we give this to community to finish or close the issue?

**Comment by pettinarip** [comment]
@konopkja yes, marking this as done.
